package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.util.*;
public class ActiveRecallFragment extends Fragment{
 private static final String ARG_MAX="max";private List<CoreSentence> items;private int index;private CoreSentence current;private ProgressStore progress;private WordRepository words;private AudioPlayer audio;private TextView stats,level,prompt,answer,feedback;private EditText input;private View next,audioBtn;private long started;
 public static ActiveRecallFragment newInstance(int max){ActiveRecallFragment f=new ActiveRecallFragment();Bundle b=new Bundle();b.putInt(ARG_MAX,max);f.setArguments(b);return f;}
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater inf,@Nullable ViewGroup c,@Nullable Bundle s){View v=inf.inflate(R.layout.fragment_active_recall,c,false);progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);int max=getArguments()==null?300:getArguments().getInt(ARG_MAX,300);items=CoreSentenceRepository.get(requireContext()).tier(max);Collections.shuffle(items);int count=progress.sessionMinutes()<=15?8:(progress.sessionMinutes()>=60?24:14);items=new ArrayList<>(items.subList(0,Math.min(count,items.size())));stats=v.findViewById(R.id.text_ar_stats);level=v.findViewById(R.id.text_ar_level);prompt=v.findViewById(R.id.text_ar_prompt);answer=v.findViewById(R.id.text_ar_answer);feedback=v.findViewById(R.id.text_ar_feedback);input=v.findViewById(R.id.edit_ar_answer);next=v.findViewById(R.id.button_ar_next);audioBtn=v.findViewById(R.id.button_ar_audio);v.findViewById(R.id.button_ar_check).setOnClickListener(x->check(false));v.findViewById(R.id.button_ar_reveal).setOnClickListener(x->check(true));audioBtn.setOnClickListener(x->{if(current!=null)audio.speak(current.italian);});next.setOnClickListener(x->{index++;show();});show();return v;}
 private void show(){if(index>=items.size()){stats.setText("本轮完成 · 历史主动回忆正确率 "+progress.auxiliaryAccuracy("active_recall")+"%");level.setText("✓ 完成");prompt.setText("今天的主动回忆结束了");input.setVisibility(View.GONE);return;}current=items.get(index);stats.setText("第 "+(index+1)+" / "+items.size()+" 句 · 历史正确率 "+progress.auxiliaryAccuracy("active_recall")+"%");level.setText(current.level+" · "+current.category);prompt.setText(current.chinese);input.setText("");input.setEnabled(true);input.setVisibility(View.VISIBLE);answer.setVisibility(View.GONE);feedback.setText("");next.setVisibility(View.GONE);audioBtn.setVisibility(View.GONE);started=System.currentTimeMillis();}
 private void check(boolean reveal){if(current==null||!input.isEnabled())return;String typed=input.getText()==null?"":input.getText().toString().trim();if(!reveal&&typed.isEmpty()){input.setError("请先主动写出答案");return;}int score=reveal?0:ErrorCauseAnalyzer.analyzeSentence(current.italian,typed,words).score;boolean ok=!reveal&&score>=86;long ms=Math.max(1,System.currentTimeMillis()-started);progress.recordAuxiliaryResult("active_recall",ok,ms);SentenceFsrsRepository.recordDimension(requireContext(),"主动回忆",current.italian,current.chinese,SentenceFsrsRepository.DIM_RECALL,ok,score,null);answer.setText(current.italian+(current.note.isEmpty()?"":"\n"+current.note));answer.setVisibility(View.VISIBLE);feedback.setText(reveal?"这次记为需要重新巩固。":((ok?"✓ 回忆成功":"△ 匹配度 "+score+"% · 再完整读一遍正确答案")));feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));input.setEnabled(false);next.setVisibility(View.VISIBLE);audioBtn.setVisibility(View.VISIBLE);}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
