package com.italiano2774.nativeapp;

import android.content.Intent;import android.os.*;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import java.util.*;

public class CommuteFragment extends Fragment{
    private Spinner source;private CheckBox chinese,example;private TextView status,word,meaning;private ProgressBar progressBar;private final Handler handler=new Handler(Looper.getMainLooper());
    private final Runnable refresh=new Runnable(){public void run(){refreshUi();handler.postDelayed(this,800);}};
    @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_commute,c,false);source=v.findViewById(R.id.spinner_commute_source);chinese=v.findViewById(R.id.check_commute_chinese);example=v.findViewById(R.id.check_commute_example);status=v.findViewById(R.id.text_commute_status);word=v.findViewById(R.id.text_commute_word);meaning=v.findViewById(R.id.text_commute_meaning);progressBar=v.findViewById(R.id.progress_commute);List<String> labels=Arrays.asList("今日自适应任务","到期复习","错词本","收藏词","生活场景100句");ArrayAdapter<String> a=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,labels);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);source.setAdapter(a);v.findViewById(R.id.button_commute_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_commute_start).setOnClickListener(x->start());v.findViewById(R.id.button_commute_pause).setOnClickListener(x->send(CommuteAudioService.ACTION_TOGGLE));v.findViewById(R.id.button_commute_next).setOnClickListener(x->send(CommuteAudioService.ACTION_NEXT));v.findViewById(R.id.button_commute_stop).setOnClickListener(x->send(CommuteAudioService.ACTION_STOP));handler.post(refresh);return v;}
    private void start(){((MainActivity)requireActivity()).requestNotificationPermissionIfNeeded();Intent i=new Intent(requireContext(),CommuteAudioService.class).setAction(CommuteAudioService.ACTION_START);i.putExtra("source",source.getSelectedItemPosition());i.putExtra("chinese",chinese.isChecked());i.putExtra("example",example.isChecked());ContextCompat.startForegroundService(requireContext(),i);Toast.makeText(requireContext(),"通勤播放已启动，可锁屏继续听",Toast.LENGTH_SHORT).show();}
    private void send(String action){if(!CommuteAudioService.running){Toast.makeText(requireContext(),"请先开始通勤播放",Toast.LENGTH_SHORT).show();return;}Intent i=new Intent(requireContext(),CommuteAudioService.class).setAction(action);requireContext().startService(i);}
    private void refreshUi(){if(CommuteAudioService.running){status.setText((CommuteAudioService.paused?"已暂停 · ":"播放中 · ")+CommuteAudioService.sourceLabel+" · "+(CommuteAudioService.currentIndex+1)+" / "+CommuteAudioService.total);word.setText(CommuteAudioService.currentWord);meaning.setText(CommuteAudioService.currentMeaning);int pct=CommuteAudioService.total<=0?0:(int)Math.round((CommuteAudioService.currentIndex+1)*100.0/CommuteAudioService.total);progressBar.setProgress(pct);}else{status.setText("尚未开始");word.setText("—");meaning.setText("选择内容后开始播放");progressBar.setProgress(0);}}
    @Override public void onDestroyView(){handler.removeCallbacks(refresh);super.onDestroyView();}
}
