package com.italiano2774.nativeapp;

import android.app.*;import android.content.*;import android.os.*;import android.speech.tts.*;import androidx.annotation.Nullable;import androidx.core.app.NotificationCompat;import java.util.*;import java.time.LocalDate;

public class CommuteAudioService extends Service{
    public static final String ACTION_START="com.italiano2774.nativeapp.COMMUTE_START";
    public static final String ACTION_TOGGLE="com.italiano2774.nativeapp.COMMUTE_TOGGLE";
    public static final String ACTION_NEXT="com.italiano2774.nativeapp.COMMUTE_NEXT";
    public static final String ACTION_STOP="com.italiano2774.nativeapp.COMMUTE_STOP";
    private static final String CHANNEL="commute_audio";private static final int NOTIF=7123;
    public static volatile boolean running=false,paused=false;public static volatile int currentIndex=0,total=0;public static volatile String currentWord="",currentMeaning="",sourceLabel="";
    private TextToSpeech tts;private android.os.PowerManager.WakeLock wakeLock;private boolean ttsReady=false,pendingStart=false,includeChinese=true,includeExample=true;private int step=0;private final Handler handler=new Handler(Looper.getMainLooper());private final List<Item> items=new ArrayList<>();
    private static class Item{String it,zh,example;Item(String i,String z,String e){it=i;zh=z;example=e;}}

    @Override public void onCreate(){super.onCreate();createChannel();android.os.PowerManager pm=(android.os.PowerManager)getSystemService(POWER_SERVICE);wakeLock=pm.newWakeLock(android.os.PowerManager.PARTIAL_WAKE_LOCK,"Italiano2774:Commute");wakeLock.acquire();tts=new TextToSpeech(getApplicationContext(),status->{if(status==TextToSpeech.SUCCESS){ttsReady=true;tts.setSpeechRate(0.90f);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onError(String id){onDone(id);}public void onDone(String id){handler.postDelayed(()->{if(running&&!paused)advanceStep();},550);}});if(pendingStart){pendingStart=false;speakCurrent();}}});}
    @Override public int onStartCommand(Intent intent,int flags,int startId){String action=intent==null?ACTION_START:intent.getAction();if(ACTION_STOP.equals(action)){stopSelf();return START_NOT_STICKY;}if(ACTION_TOGGLE.equals(action)){paused=!paused;if(tts!=null)tts.stop();if(!paused&&running)speakCurrent();updateNotification();return START_STICKY;}if(ACTION_NEXT.equals(action)){if(tts!=null)tts.stop();nextItem();return START_STICKY;}int source=intent==null?0:intent.getIntExtra("source",0);includeChinese=intent==null||intent.getBooleanExtra("chinese",true);includeExample=intent==null||intent.getBooleanExtra("example",true);buildItems(source);running=!items.isEmpty();paused=false;currentIndex=0;step=0;startForeground(NOTIF,notification());if(running){if(ttsReady)speakCurrent();else pendingStart=true;}else stopSelf();return START_STICKY;}
    private void buildItems(int source){items.clear();ProgressStore progress=new ProgressStore(this);WordRepository repo=WordRepository.get(this);List<Word> words=new ArrayList<>();if(source==0){DailyPlan p=repo.adaptivePlan(progress);words.addAll(p.words);sourceLabel="今日自适应任务";}else if(source==1){words.addAll(repo.reviewDue(progress,LocalDate.now()));sourceLabel="到期复习";}else if(source==2){words.addAll(repo.wrongWords(progress));sourceLabel="错词本";}else if(source==3){for(Word w:repo.all())if(progress.favorite(w.id))words.add(w);sourceLabel="收藏词";}else{sourceLabel="生活场景100句";for(Scenario s:ScenarioRepository.get(this).all())for(ScenarioPhrase p:s.phrases)items.add(new Item(p.it,p.zh,""));}
        if(source<4){for(Word w:words){String zh=w.chinese==null||w.chinese.isEmpty()?w.english:w.chinese;items.add(new Item(w.word,zh,ExampleQuality.isUsable(w)?w.example:""));}}
        total=items.size();if(total==0){currentWord="";currentMeaning="";}}
    private void speakCurrent(){if(!running||paused||items.isEmpty()||currentIndex>=items.size())return;Item item=items.get(currentIndex);currentWord=item.it;currentMeaning=item.zh;updateNotification();speakStep(item);}
    private void speakStep(Item item){if(!ttsReady||paused)return;Locale locale=(step==1&&includeChinese)?Locale.SIMPLIFIED_CHINESE:Locale.ITALIAN;int lang=tts.setLanguage(locale);if(step==1&&lang<0){step=2;speakStep(item);return;}String text;if(step==0)text=item.it;else if(step==1)text=includeChinese?item.zh:item.it;else if(step==2)text=item.it;else text=includeExample&&item.example!=null&&!item.example.isEmpty()?item.example:item.it;tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"commute_"+currentIndex+"_"+step+"_"+System.nanoTime());}
    private void advanceStep(){if(!running||paused)return;Item item=items.get(currentIndex);if(step==0){step=includeChinese?1:2;speakStep(item);return;}if(step==1){step=2;speakStep(item);return;}if(step==2&&includeExample&&item.example!=null&&!item.example.isEmpty()){step=3;speakStep(item);return;}nextItem();}
    private void nextItem(){if(items.isEmpty())return;currentIndex++;step=0;if(currentIndex>=items.size()){currentIndex=0;}if(running&&!paused)speakCurrent();else updateNotification();}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"通勤听力",NotificationManager.IMPORTANCE_LOW);c.setDescription("锁屏继续播放意大利语学习内容");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    private PendingIntent action(String a,int code){Intent i=new Intent(this,CommuteAudioService.class).setAction(a);return PendingIntent.getService(this,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
    private Notification notification(){String line=running&&total>0?(currentIndex+1)+" / "+total+" · "+currentWord:"准备播放";return new NotificationCompat.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_launcher).setContentTitle("终学意语 · "+sourceLabel).setContentText(line).setOngoing(true).setOnlyAlertOnce(true).addAction(android.R.drawable.ic_media_pause,paused?"继续":"暂停",action(ACTION_TOGGLE,1)).addAction(android.R.drawable.ic_media_next,"下一条",action(ACTION_NEXT,2)).addAction(android.R.drawable.ic_menu_close_clear_cancel,"停止",action(ACTION_STOP,3)).build();}
    private void updateNotification(){if(running){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.notify(NOTIF,notification());}}
    @Override public void onDestroy(){running=false;paused=false;currentIndex=0;total=0;currentWord="";currentMeaning="";handler.removeCallbacksAndMessages(null);if(tts!=null){tts.stop();tts.shutdown();tts=null;}if(wakeLock!=null&&wakeLock.isHeld())wakeLock.release();stopForeground(true);super.onDestroy();}
    @Nullable @Override public android.os.IBinder onBind(Intent intent){return null;}
}
