package com.italiano2774.nativeapp;
import android.os.Bundle;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.appcompat.app.AlertDialog;import androidx.fragment.app.Fragment;import androidx.recyclerview.widget.LinearLayoutManager;import androidx.recyclerview.widget.RecyclerView;import java.util.*;
public class CustomLibraryFragment extends Fragment implements TextToSpeech.OnInitListener{
 private TextToSpeech tts;private EditText it,zh,note;private Spinner kind;private CheckBox dueOnly;private TextView stats;private CustomItemAdapter adapter;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_custom_library,c,false);tts=new TextToSpeech(requireContext(),this);it=v.findViewById(R.id.edit_custom_it);zh=v.findViewById(R.id.edit_custom_zh);note=v.findViewById(R.id.edit_custom_note);kind=v.findViewById(R.id.spinner_custom_kind);dueOnly=v.findViewById(R.id.check_custom_due);stats=v.findViewById(R.id.text_custom_stats);ArrayAdapter<String> ka=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,new String[]{"单词","句子"});ka.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);kind.setAdapter(ka);RecyclerView rv=v.findViewById(R.id.recycler_custom);rv.setLayoutManager(new LinearLayoutManager(requireContext()));adapter=new CustomItemAdapter(new CustomItemAdapter.Actions(){public void speak(CustomStudyItem x){say(x.italian);}public void review(CustomStudyItem x,boolean correct){CustomLibraryRepository.review(requireContext(),x,correct,z->refresh());}public void delete(CustomStudyItem x){new AlertDialog.Builder(requireContext()).setMessage("删除“"+x.italian+"”？").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->CustomLibraryRepository.delete(requireContext(),x,z->refresh())).show();}});rv.setAdapter(adapter);v.findViewById(R.id.button_add_custom).setOnClickListener(x->add());dueOnly.setOnCheckedChangeListener((b,x)->refresh());refresh();return v;}
 private void add(){String a=it.getText().toString().trim();if(a.isEmpty()){it.setError("请输入意大利语");return;}String k=kind.getSelectedItemPosition()==1?"sentence":"word";CustomLibraryRepository.add(requireContext(),k,a,zh.getText().toString(),note.getText().toString(),id->{Toast.makeText(requireContext(),"已加入个人学习库",Toast.LENGTH_SHORT).show();it.setText("");zh.setText("");note.setText("");refresh();});}
 private void refresh(){CustomLibraryRepository.Callback<List<CustomStudyItem>> cb=list->{adapter.submit(list);int due=0;long today=java.time.LocalDate.now().toEpochDay();for(CustomStudyItem x:list)if(x.dueEpochDay<=today)due++;stats.setText("共 "+list.size()+" 项 · 今天到期 "+due+" · 会/不会会自动调整下次复习时间");};if(dueOnly!=null&&dueOnly.isChecked())CustomLibraryRepository.due(requireContext(),cb);else CustomLibraryRepository.all(requireContext(),cb);}
 private void say(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"custom");}
 public void onInit(int status){if(status==TextToSpeech.SUCCESS)tts.setLanguage(Locale.ITALY);}
 @Override public void onDestroyView(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroyView();}
}
