package com.italiano2774.nativeapp;
import android.view.*;import android.widget.*;import androidx.annotation.NonNull;import androidx.recyclerview.widget.RecyclerView;import java.time.LocalDate;import java.util.*;
public class CustomItemAdapter extends RecyclerView.Adapter<CustomItemAdapter.H>{
 public interface Actions{void speak(CustomStudyItem x);void review(CustomStudyItem x,boolean correct);void delete(CustomStudyItem x);}private final Actions a;private final List<CustomStudyItem> items=new ArrayList<>();
 public CustomItemAdapter(Actions x){a=x;}public void submit(List<CustomStudyItem> d){items.clear();items.addAll(d);notifyDataSetChanged();}
 @NonNull public H onCreateViewHolder(@NonNull ViewGroup p,int v){return new H(LayoutInflater.from(p.getContext()).inflate(R.layout.item_custom_study,p,false));}
 public void onBindViewHolder(@NonNull H h,int pos){CustomStudyItem x=items.get(pos);h.kind.setText(x.kind.equals("sentence")?"句子":"单词");h.it.setText(x.italian);h.zh.setText(x.chinese.isEmpty()?"尚未填写中文释义":x.chinese);h.note.setVisibility(x.note.isEmpty()?View.GONE:View.VISIBLE);h.note.setText(x.note);long today=LocalDate.now().toEpochDay();h.due.setText(x.dueEpochDay<=today?"今天复习":("下次 "+LocalDate.ofEpochDay(x.dueEpochDay)));h.speak.setOnClickListener(v->a.speak(x));h.wrong.setOnClickListener(v->a.review(x,false));h.right.setOnClickListener(v->a.review(x,true));h.delete.setOnClickListener(v->a.delete(x));}
 public int getItemCount(){return items.size();}
 static class H extends RecyclerView.ViewHolder{TextView kind,it,zh,note,due;View speak,wrong,right,delete;H(View v){super(v);kind=v.findViewById(R.id.text_custom_kind);it=v.findViewById(R.id.text_custom_it);zh=v.findViewById(R.id.text_custom_zh);note=v.findViewById(R.id.text_custom_note);due=v.findViewById(R.id.text_custom_due);speak=v.findViewById(R.id.button_custom_speak);wrong=v.findViewById(R.id.button_custom_wrong);right=v.findViewById(R.id.button_custom_right);delete=v.findViewById(R.id.button_custom_delete);}}
}
