package com.italiano2774.nativeapp;
import android.content.Context;import java.time.LocalDate;import java.util.*;import java.util.concurrent.ExecutorService;import java.util.concurrent.Executors;
public class CustomLibraryRepository{
 public interface Callback<T>{void done(T value);} private static final ExecutorService IO=Executors.newSingleThreadExecutor();
 public static void all(Context c,Callback<List<CustomStudyItem>> cb){Context app=c.getApplicationContext();IO.execute(()->{List<CustomStudyItem> x=LearningDatabase.get(app).customStudyItemDao().all();android.os.Handler h=new android.os.Handler(android.os.Looper.getMainLooper());h.post(()->cb.done(x));});}
 public static void due(Context c,Callback<List<CustomStudyItem>> cb){Context app=c.getApplicationContext();long d=LocalDate.now().toEpochDay();IO.execute(()->{List<CustomStudyItem> x=LearningDatabase.get(app).customStudyItemDao().due(d);new android.os.Handler(android.os.Looper.getMainLooper()).post(()->cb.done(x));});}
 public static void add(Context c,String kind,String it,String zh,String note,Callback<Long> cb){Context app=c.getApplicationContext();IO.execute(()->{CustomStudyItemDao dao=LearningDatabase.get(app).customStudyItemDao();CustomStudyItem old=dao.find(kind,it.trim());long id;if(old!=null){old.chinese=zh==null?old.chinese:zh.trim();old.note=note==null?old.note:note.trim();dao.update(old);id=old.id;}else{CustomStudyItem x=new CustomStudyItem();x.kind=kind==null?"word":kind;x.italian=it.trim();x.chinese=zh==null?"":zh.trim();x.note=note==null?"":note.trim();x.createdAt=System.currentTimeMillis();x.dueEpochDay=LocalDate.now().toEpochDay();x.intervalDays=0;id=dao.insert(x);}LearningDatabase.log(app,"custom_add",String.valueOf(id),-1,true,0,xDetail(it));if(cb!=null)new android.os.Handler(android.os.Looper.getMainLooper()).post(()->cb.done(id));});}
 private static String xDetail(String s){return s==null?"":s;}
 public static void review(Context c,CustomStudyItem item,boolean correct,Callback<CustomStudyItem> cb){Context app=c.getApplicationContext();IO.execute(()->{item.attempts++;if(correct)item.correct++;if(correct){item.difficulty=Math.max(1.0,item.difficulty-0.2);item.stability=Math.max(1.0,item.stability*(item.attempts<=2?1.8:1.55));item.intervalDays=Math.max(1,Math.min(180,(int)Math.round(item.stability)));}else{item.difficulty=Math.min(10.0,item.difficulty+0.7);item.stability=Math.max(1.0,item.stability*0.45);item.intervalDays=1;}item.dueEpochDay=LocalDate.now().plusDays(item.intervalDays).toEpochDay();LearningDatabase.get(app).customStudyItemDao().update(item);LearningDatabase.log(app,"custom_review",String.valueOf(item.id),-1,correct,0,item.kind);if(cb!=null)new android.os.Handler(android.os.Looper.getMainLooper()).post(()->cb.done(item));});}
 public static void delete(Context c,CustomStudyItem item,Callback<Boolean> cb){Context app=c.getApplicationContext();IO.execute(()->{LearningDatabase.get(app).customStudyItemDao().delete(item);if(cb!=null)new android.os.Handler(android.os.Looper.getMainLooper()).post(()->cb.done(true));});}
}
