package com.italiano2774.nativeapp;

import android.content.res.ColorStateList;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import java.util.*;

public class DialogueTrainingFragment extends Fragment{
    public static DialogueTrainingFragment newInstance(String id){DialogueTrainingFragment f=new DialogueTrainingFragment();Bundle b=new Bundle();b.putString("scenario",id==null?"":id);f.setArguments(b);return f;}
    private DialogueRepository repo;private ProgressStore progress;private AudioPlayer audio;private Spinner spinner;private TextView stats,turnProgress,npc,npcZh,feedback,reply;private final List<MaterialButton> choices=new ArrayList<>();private MaterialButton next;private DialogueScenario current;private int turnIndex=0;private boolean answered=false;private long startedAt=0L;
    @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle state){
        View v=i.inflate(R.layout.fragment_dialogue_training,c,false);repo=DialogueRepository.get(requireContext());progress=new ProgressStore(requireContext());audio=new AudioPlayer(requireContext(),progress);spinner=v.findViewById(R.id.spinner_dialogue);stats=v.findViewById(R.id.text_dialogue_stats);turnProgress=v.findViewById(R.id.text_dialogue_progress);npc=v.findViewById(R.id.text_dialogue_npc);npcZh=v.findViewById(R.id.text_dialogue_npc_zh);feedback=v.findViewById(R.id.text_dialogue_feedback);reply=v.findViewById(R.id.text_dialogue_reply);next=v.findViewById(R.id.button_dialogue_next);choices.add(v.findViewById(R.id.button_dialogue_choice1));choices.add(v.findViewById(R.id.button_dialogue_choice2));choices.add(v.findViewById(R.id.button_dialogue_choice3));
        v.findViewById(R.id.button_dialogue_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_dialogue_replay).setOnClickListener(x->{DialogueTurn t=currentTurn();if(t!=null)audio.speak(t.npc);});v.findViewById(R.id.button_dialogue_restart).setOnClickListener(x->{turnIndex=0;showTurn();});next.setOnClickListener(x->advance());
        List<String> names=new ArrayList<>();for(DialogueScenario d:repo.all())names.add(d.emoji+"  "+d.title);ArrayAdapter<String> a=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,names);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);spinner.setAdapter(a);spinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(pos>=0&&pos<repo.all().size()){current=repo.all().get(pos);turnIndex=0;showTurn();}}});String wanted=getArguments()==null?"":getArguments().getString("scenario","");if(!wanted.isEmpty()){for(int n=0;n<repo.all().size();n++)if(repo.all().get(n).id.equals(wanted)){spinner.setSelection(n);break;}}refreshStats();return v;
    }
    private DialogueTurn currentTurn(){if(current==null||current.turns.isEmpty())return null;return current.turns.get(Math.min(turnIndex,current.turns.size()-1));}
    private void showTurn(){DialogueTurn t=currentTurn();if(t==null)return;answered=false;startedAt=System.currentTimeMillis();turnProgress.setText(current.emoji+" "+current.title+" · 第 "+(turnIndex+1)+" / "+current.turns.size()+" 轮");npc.setText(t.npc);npcZh.setText(t.npcZh);feedback.setText("");reply.setVisibility(View.GONE);next.setVisibility(View.GONE);for(int i=0;i<choices.size();i++){MaterialButton b=choices.get(i);b.setEnabled(true);b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(requireContext(),R.color.line)));b.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_primary));String label=i<t.choices.size()?t.choices.get(i):"";b.setText(label);final int idx=i;b.setOnClickListener(x->choose(idx));}npc.postDelayed(()->{DialogueTurn x=currentTurn();if(x!=null)audio.speak(x.npc);},250);}
    private void choose(int idx){if(answered)return;DialogueTurn t=currentTurn();if(t==null)return;boolean ok=idx==t.correct;long ms=Math.max(1,System.currentTimeMillis()-startedAt);progress.recordAuxiliaryResult("dialogue",ok,ms);if(!ok)progress.recordErrorCause(ErrorCause.MEANING_CONFUSION,0,"dialogue",t.choices.get(t.correct),t.choices.get(idx),"情景应答选择");answered=ok;MaterialButton b=choices.get(Math.max(0,Math.min(idx,choices.size()-1)));b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error)));b.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));if(ok){for(MaterialButton x:choices)x.setEnabled(false);feedback.setText("✓ 回答合适");feedback.setTextColor(ContextCompat.getColor(requireContext(),R.color.success));String user=t.choices.get(t.correct);reply.setText("你："+user+"\n\n对方："+t.reply+"\n"+t.replyZh);reply.setVisibility(View.VISIBLE);audio.speak(user+". "+t.reply);next.setVisibility(View.VISIBLE);next.setText(turnIndex+1>=current.turns.size()?"完成并重新开始":"继续对话 →");}else{feedback.setText("再想一下，这句不适合当前场景");feedback.setTextColor(ContextCompat.getColor(requireContext(),R.color.error));}refreshStats();}
    private void advance(){if(current==null)return;if(turnIndex+1>=current.turns.size()){turnIndex=0;Toast.makeText(requireContext(),"完成一个真实场景对话 ✓",Toast.LENGTH_SHORT).show();}else turnIndex++;showTurn();}
    private void refreshStats(){stats.setText("对话练习："+progress.auxiliaryAttempts("dialogue")+" 次选择 · 正确率 "+progress.auxiliaryAccuracy("dialogue")+"% · 先理解对方，再选择自然回应");}
    @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
