package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.text.Normalizer;import java.time.LocalDate;import java.util.*;
public class FocusModeFragment extends Fragment{
 private static class Task{boolean sentence;int wordId;String prompt="",answer="",zh="",source="";}
 private final List<Task> tasks=new ArrayList<>();private int index,correct;private ProgressStore progress;private WordRepository words;private AudioPlayer audio;private TextView stats,type,prompt,feedback;private EditText input;private ProgressBar bar;private long started;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_focus_mode,c,false);progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);((MainActivity)requireActivity()).setFocusUi(true);stats=v.findViewById(R.id.text_focus_stats);type=v.findViewById(R.id.text_focus_type);prompt=v.findViewById(R.id.text_focus_prompt);feedback=v.findViewById(R.id.text_focus_feedback);input=v.findViewById(R.id.edit_focus_answer);bar=v.findViewById(R.id.progress_focus);v.findViewById(R.id.button_focus_exit).setOnClickListener(x->{((MainActivity)requireActivity()).setFocusUi(false);((MainActivity)requireActivity()).openToday(LocalDate.now());});v.findViewById(R.id.button_focus_audio).setOnClickListener(x->{Task t=current();if(t!=null)audio.speak(t.answer);});v.findViewById(R.id.button_focus_check).setOnClickListener(x->check());build();show();return v;}
 private void build(){int n=progress.sessionMinutes()<=5?6:(progress.sessionMinutes()<=15?12:(progress.sessionMinutes()>=60?36:22));List<Word> candidates=new ArrayList<>();long today=LocalDate.now().toEpochDay();int limit=Math.min(progress.vocabularyRouteLimit(),words.size());for(int i=0;i<limit;i++){Word w=words.all().get(i);if(progress.isGraduated(w.id))continue;if(progress.dueEpochDay(w.id)<=today||progress.mastery(w.id)<3)candidates.add(w);}candidates.sort((a,b)->Long.compare(progress.dueEpochDay(a.id),progress.dueEpochDay(b.id)));List<CoreSentence> ss=CoreSentenceRepository.get(requireContext()).tier(300);Collections.shuffle(ss);int wi=0,si=0;while(tasks.size()<n&&(wi<candidates.size()||si<ss.size())){if(tasks.size()%3==2&&si<ss.size()){CoreSentence s=ss.get(si++);Task t=new Task();t.sentence=true;t.prompt=s.chinese;t.answer=s.italian;t.zh=s.chinese;t.source="核心句";tasks.add(t);}else if(wi<candidates.size()){Word w=candidates.get(wi++);Task t=new Task();t.wordId=w.id;t.prompt=w.chinese;t.answer=w.word;t.zh=w.chinese;t.source="词汇";tasks.add(t);}else if(si<ss.size()){CoreSentence s=ss.get(si++);Task t=new Task();t.sentence=true;t.prompt=s.chinese;t.answer=s.italian;t.zh=s.chinese;t.source="核心句";tasks.add(t);}}}
 private Task current(){return index<tasks.size()?tasks.get(index):null;}
 private void show(){if(index>=tasks.size()){bar.setProgress(100);stats.setText("专注完成 · "+correct+" / "+tasks.size()+" 正确");type.setText("✓ 今日专注完成");prompt.setText("可以结束本次学习，让记忆休息一下。 ");input.setVisibility(View.GONE);progress.recordAuxiliaryResult("focus_mode",true,0);return;}Task t=current();bar.setProgress((int)Math.round(index*100.0/Math.max(1,tasks.size())));stats.setText("第 "+(index+1)+" / "+tasks.size()+" 项 · 已正确 "+correct);type.setText(t.sentence?"完整句子主动回忆":"高收益词汇回忆");prompt.setText(t.prompt);input.setText("");input.setEnabled(true);input.setVisibility(View.VISIBLE);feedback.setText("");started=System.currentTimeMillis();}
 private void check(){Task t=current();if(t==null)return;String typed=input.getText()==null?"":input.getText().toString().trim();if(typed.isEmpty()){input.setError("请先写出答案");return;}int score=t.sentence?ErrorCauseAnalyzer.analyzeSentence(t.answer,typed,words).score:(norm(t.answer).equals(norm(typed))?100:0);boolean ok=score>=86;long ms=Math.max(1,System.currentTimeMillis()-started);if(ok)correct++;if(t.sentence){SentenceFsrsRepository.recordDimension(requireContext(),"专注模式",t.answer,t.zh,SentenceFsrsRepository.DIM_RECALL,ok,score,null);}else{progress.recordDimensionResult(t.wordId,ProgressStore.DIM_MEANING,ok,ms);}progress.recordAuxiliarySubskill("focus_mode",ok,ms);feedback.setText((ok?"✓":"△")+" "+(ok?"正确":"正确答案："+t.answer));feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));input.setEnabled(false);input.postDelayed(()->{index++;show();},ok?450:1300);}
 private String norm(String s){return Normalizer.normalize(s==null?"":s,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ITALIAN).replaceAll("[^a-z0-9]","");}
 @Override public void onDestroyView(){((MainActivity)requireActivity()).setFocusUi(false);if(audio!=null)audio.release();super.onDestroyView();}
}
