package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import com.google.android.material.card.MaterialCardView;import java.util.*;
public class GrammarMapFragment extends Fragment{
 private ProgressStore progress;private SentencePatternRepository repo;private LinearLayout container;private TextView summary;private String level="A1";
 private static final String[] A1={"vorrei","bisogno","potere","dovere","c_e","piacere","quanto_costa","dove_posso","mi_serve","perche","non_ho_capito"};
 private static final String[] A2={"stare_gerundio","da_quanto","prima_dopo","passato_prossimo","imperfetto","comparativo","ci_vuole","vorrei_sapere","ce_l_ho"};
 private static final String[] B1={"se_presente","futuro_semplice","condizionale_presente","pronomi_diretti","pronomi_indiretti","imperativo","ne_partitivo"};
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_grammar_map,c,false);progress=new ProgressStore(requireContext());repo=SentencePatternRepository.get(requireContext());container=v.findViewById(R.id.container_grammar_map);summary=v.findViewById(R.id.text_grammar_map_summary);v.findViewById(R.id.button_grammar_map_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_grammar_map_a1).setOnClickListener(x->{level="A1";render();});v.findViewById(R.id.button_grammar_map_a2).setOnClickListener(x->{level="A2";render();});v.findViewById(R.id.button_grammar_map_b1).setOnClickListener(x->{level="B1";render();});render();return v;}
 private void render(){String[] ids="A2".equals(level)?A2:("B1".equals(level)?B1:A1);container.removeAllViews();int total=0,solid=0,attempts=0;for(String id:ids){SentencePattern p=find(id);if(p==null)continue;int a=progress.grammarAttempts(id),acc=progress.grammarAccuracy(id);int score=a==0?0:(int)Math.round(acc*Math.min(1.0,a/3.0));total+=score;attempts+=a;if(score>=80)solid++;addCard(p,a,acc,score);}int avg=ids.length==0?0:(int)Math.round(total/(double)ids.length);summary.setText(level+" 语法地图 · 稳定 "+solid+" / "+ids.length+" · 综合 "+avg+"% · 已练 "+attempts+"题\n绿色=基本稳定，黄色=需要巩固，红色=优先补课，灰色=尚未开始");}
 private void addCard(SentencePattern p,int attempts,int acc,int score){MaterialCardView card=new MaterialCardView(requireContext());card.setRadius(dp(16));card.setCardElevation(0);int stroke=score>=80?R.color.level4:(score>=55?R.color.level3:(attempts==0?R.color.line:R.color.error));card.setStrokeColor(ContextCompat.getColor(requireContext(),stroke));card.setStrokeWidth(dp(1));card.setCardBackgroundColor(ContextCompat.getColor(requireContext(),R.color.surface));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);cp.setMargins(0,dp(5),0,dp(5));container.addView(card,cp);LinearLayout box=new LinearLayout(requireContext());box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));card.addView(box);TextView t=new TextView(requireContext());t.setText(p.title);t.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_primary));t.setTextSize(16);t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);box.addView(t);TextView f=new TextView(requireContext());f.setText(p.formula);f.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_secondary));f.setTextSize(12);box.addView(f);ProgressBar bar=new ProgressBar(requireContext(),null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);bar.setProgress(score);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(6));bp.setMargins(0,dp(9),0,dp(5));box.addView(bar,bp);TextView st=new TextView(requireContext());st.setText(attempts==0?"尚未练习":("正确率 "+acc+"% · "+attempts+"题 · 稳定度 "+score+"% · 间隔 "+progress.grammarIntervalDays(p.id)+"天"+(progress.grammarDue(p.id)?" · 🔄 到期":"")));st.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_secondary));st.setTextSize(11);box.addView(st);MaterialButton b=new MaterialButton(requireContext());b.setAllCaps(false);b.setText(attempts==0?"开始学习":"针对训练");b.setOnClickListener(v->((MainActivity)requireActivity()).openSentencePatterns(p.id));LinearLayout.LayoutParams mb=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(44));mb.setMargins(0,dp(8),0,0);box.addView(b,mb);}
 private SentencePattern find(String id){for(SentencePattern p:repo.all())if(p.id.equals(id))return p;return null;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
