package com.italiano2774.nativeapp;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.os.Bundle;import android.speech.*;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.util.*;
/** v2.7 six-step intensive listening with dictation + no-caption retelling. */
public class IntensiveListeningFragment extends Fragment{
 private static final int REQ_AUDIO=781;private ProgressStore progress;private WordRepository words;private AudioPlayer audio;private List<SentenceDictationItem> items;private int index=0;private SentenceDictationItem current;private TextView stats,source,italian,chinese,feedback,stage;private EditText input;private View next,speak;private long started;private SpeechRecognizer recognizer;private int listenScore;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_intensive_listening,c,false);progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);items=new SentenceDictationRepository(requireContext()).session(progress.sessionMinutes()>=30?10:6);stats=v.findViewById(R.id.text_il_stats);source=v.findViewById(R.id.text_il_source);italian=v.findViewById(R.id.text_il_italian);chinese=v.findViewById(R.id.text_il_chinese);feedback=v.findViewById(R.id.text_il_feedback);stage=v.findViewById(R.id.text_il_stage);input=v.findViewById(R.id.edit_il_answer);next=v.findViewById(R.id.button_il_next);speak=v.findViewById(R.id.button_il_speak_check);v.findViewById(R.id.button_il_play).setOnClickListener(x->play(.94f));v.findViewById(R.id.button_il_slow).setOnClickListener(x->play(.72f));v.findViewById(R.id.button_il_show_it).setOnClickListener(x->{italian.setVisibility(View.VISIBLE);stage.setText("3/6 看字幕再听");play(.88f);});v.findViewById(R.id.button_il_show_zh).setOnClickListener(x->{chinese.setVisibility(View.VISIBLE);stage.setText("4/6 理解句意");});v.findViewById(R.id.button_il_submit).setOnClickListener(x->submit());v.findViewById(R.id.button_il_shadow).setOnClickListener(x->{play(.86f);stage.setText("6/6 跟读后，尝试无字幕复述");});speak.setOnClickListener(x->requestSpeech());next.setOnClickListener(x->{index++;show();});show();return v;}
 private void show(){feedback.setText("");input.setText("");input.setEnabled(true);input.setVisibility(View.VISIBLE);italian.setVisibility(View.GONE);chinese.setVisibility(View.GONE);next.setVisibility(View.GONE);speak.setEnabled(true);listenScore=0;if(index>=items.size()){source.setText("本轮精听完成");stage.setText("建议把没有听清和复述失败的句子交给句子FSRS继续复习");input.setVisibility(View.GONE);speak.setVisibility(View.GONE);return;}speak.setVisibility(View.VISIBLE);current=items.get(index);stats.setText("第 "+(index+1)+" / "+items.size()+" 句 · 精听历史 "+progress.auxiliaryAttempts("intensive_listening")+" 次");source.setText(current.source);italian.setText(current.italian);chinese.setText(current.chinese+(current.note.isEmpty()?"":"\n"+current.note));stage.setText("1/6 先只听两遍，不看字幕");started=System.currentTimeMillis();input.postDelayed(()->play(.94f),250);}
 private void play(float r){if(current!=null)audio.speak(current.italian,r);}
 private void submit(){if(current==null||!input.isEnabled())return;String typed=input.getText()==null?"":input.getText().toString().trim();if(typed.isEmpty()){input.setError("请写下听到的句子");return;}ErrorCauseAnalyzer.SentenceAnalysis a=ErrorCauseAnalyzer.analyzeSentence(current.italian,typed,words);listenScore=a.score;boolean ok=a.score>=90;long ms=System.currentTimeMillis()-started;progress.recordAuxiliaryResult("intensive_listening",ok,ms);SentenceFsrsRepository.recordDimension(requireContext(),current.source,current.italian,current.chinese,SentenceFsrsRepository.DIM_LISTENING,ok,a.score,null);if(!ok){for(String cause:a.causes)progress.recordErrorCause(cause,0,"intensive_listening",current.italian,typed,a.summary());markWeak(current.italian,typed);}feedback.setText((ok?"✓ ":"△ ")+"听写匹配度 "+a.score+"%\n"+a.summary()+"\n"+a.diff+"\n下一步：跟读，然后隐藏字幕复述。");feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));italian.setVisibility(View.VISIBLE);chinese.setVisibility(View.VISIBLE);input.setEnabled(false);stage.setText("5/6 对照错误；最后完成跟读和无字幕复述");next.setVisibility(View.VISIBLE);}
 private void requestSpeech(){if(current==null)return;if(ContextCompat.checkSelfPermission(requireContext(),Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_AUDIO);return;}startSpeech();}
 private void startSpeech(){if(!SpeechRecognizer.isRecognitionAvailable(requireContext())){feedback.setText("设备没有可用的系统语音识别服务。");return;}italian.setVisibility(View.GONE);chinese.setVisibility(View.GONE);if(recognizer!=null)recognizer.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(requireContext());recognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){stage.setText("6/6 正在听你的无字幕复述…");}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){stage.setText("没有识别清楚，可以再复述一次");}public void onResults(Bundle b){ArrayList<String> xs=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String heard=xs==null||xs.isEmpty()?"":xs.get(0);ErrorCauseAnalyzer.SentenceAnalysis a=ErrorCauseAnalyzer.analyzeSentence(current.italian,heard,words);boolean ok=a.score>=82;SentenceFsrsRepository.recordDimension(requireContext(),current.source,current.italian,current.chinese,SentenceFsrsRepository.DIM_SPEAKING,ok,a.score,null);progress.recordAuxiliarySubskill("shadowing",ok,0);feedback.setText("复述识别："+heard+"\n内容匹配度 "+a.score+"%"+(ok?" · ✓ 可以进入下一句":" · 继续跟读一遍会更稳"));feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));stage.setText("6/6 完成 · 听写 "+listenScore+"% · 复述 "+a.score+"%");italian.setVisibility(View.VISIBLE);}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"it-IT");i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);recognizer.startListening(i);}
 private void markWeak(String expected,String actual){Set<String> got=new HashSet<>(Arrays.asList(ErrorCauseAnalyzer.basic(actual).split(" ")));int n=0;for(String t:ErrorCauseAnalyzer.basic(expected).split(" ")){if(t.length()<3||got.contains(t))continue;Word w=words.lookupSurface(t);if(w!=null){progress.recordDimensionResult(w.id,ProgressStore.DIM_LISTENING,false,0);if(++n>=3)break;}}}
 @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_AUDIO&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startSpeech();}
 @Override public void onDestroyView(){if(recognizer!=null)recognizer.destroy();if(audio!=null)audio.release();super.onDestroyView();}
}
