package com.italiano2774.nativeapp;
import android.content.Context;import java.time.LocalDate;import java.util.*;
/** v2.7 adaptive path: memory pressure, listening/recall weaknesses and goal-weighted output. */
public class LearningPathEngine {
 private final Context context;private final WordRepository repo;private final ProgressStore progress;
 public LearningPathEngine(Context c,WordRepository r,ProgressStore p){context=c.getApplicationContext();repo=r;progress=p;}
 public List<LearningPathNode> build(){return build(progress.dashboardStats(repo.all(),LocalDate.now()));}
 public List<LearningPathNode> build(ProgressStore.DashboardStats stats){
  LocalDate d=LocalDate.now();if(stats==null)stats=progress.dashboardStats(repo.all(),d);int m=progress.sessionMinutes(),due=stats.due,wrong=stats.wrong,acc=stats.sevenDayAccuracy,newQuota=stats.newQuota,stubborn=stats.stubborn,pressure=stats.reviewPressure,goal=progress.learningGoal();PersonalizedCourse course=new PersonalizedCourseEngine(context,repo,progress).buildOverview(stats);int[] av=stats.learnedDimensionPct;int weak=stats.weakestDimension();
  List<LearningPathNode> c=new ArrayList<>();int cardTarget=m==5?4:(m==15?8:(m==60?20:12));int vocabPriority=85+Math.min(35,due/2)+Math.min(15,wrong/3)+(acc<78?15:0);String vocabReason=newQuota==0?"今天暂停新词，先清理到期复习和顽固词":(due>25?"到期复习积压较多":(acc<78?"最近正确率下降，先稳住旧知识":"自动调速："+stats.paceAdvice));c.add(node("vocab","🧠","记忆主线",progress.vocabularyRouteLabel()+" · 到期 "+due+" · 错词 "+wrong+" · 新词 "+newQuota,Math.min(6,m),"vocab",String.valueOf(cardTarget),progress.dailyCards(d)>=cardTarget,vocabPriority+(pressure>=2?15:0),vocabReason+"；"+stats.reviewPressureAdvice));
  if(pressure>=2)c.add(node("rescue","⚡","5分钟抢救","只取最可能遗忘的12项，不要求一次清空全部积压",5,"rescue","",progress.dailyAuxiliaryAttempts("rescue",d)>=1,135,"复习压力偏高，先做最小高收益任务"));
  if(stubborn>0)c.add(node("stubborn","🔥","顽固词冲刺","当前 "+stubborn+" 个 · 词义/听音/中文回忆/例句轮换",4,"stubborn","",progress.dailyAuxiliaryAttempts("stubborn",d)>=3,100+Math.min(25,stubborn),"反复出错的词优先换一种方式练"));
  int weakTarget=m==5?2:(m==15?4:7);c.add(node("weak","🎯",dimName(weak)+"弱项快练","当前已学词平均 "+av[weak]+"%，优先补最低维度",m==5?2:4,"practice",String.valueOf(weak),progress.dailyAttempts(d)>=weakTarget,90+(100-av[weak])/2,"四维能力最低项"));
  String topCause=progress.topErrorCause();int causeCount=progress.errorCauseCount(topCause);if(causeCount>0){String action="practice",payload=String.valueOf(causeToDim(topCause));if(ErrorCause.GRAMMAR.equals(topCause)||ErrorCause.WORD_FORM.equals(topCause)||ErrorCause.ARTICLE_GENDER.equals(topCause)){action="grammar";payload=course.grammarPatternId;}else if(ErrorCause.WORD_ORDER.equals(topCause)||ErrorCause.OMISSION.equals(topCause)){action="intensive_listening";payload="";}c.add(node("repair","🩹","错误原因修复",ErrorCause.label(topCause)+"累计 "+causeCount+" 次，今天针对性处理",4,action,payload,progress.dailyAuxiliaryAttempts("error_repair",d)>=1,95+Math.min(30,causeCount),"按真实错误原因安排"));}
  if(m>=15){c.add(node("listen_speak","🎧🗣","听说10题","听句→听词→跟读→看中文开口，错项自动回流智能复习",6,"listen_speak","",progress.dailyAuxiliaryAttempts("listen_speak",d)>=6,(weak==ProgressStore.DIM_LISTENING||weak==ProgressStore.DIM_SPEAKING)?118:92,"把认识的词真正变成听得懂、说得出的表达"));c.add(node("listening_course","🎧","分级听力课程","A1→A2→B1，按当前阶段练真实生活句",5,"listening_course","",progress.dailyAuxiliaryAttempts("listening_course",d)>=2,weak==ProgressStore.DIM_LISTENING?108:82,"听力低时优先进入分级课程"));c.add(node("intensive","🎧","逐句精听2.0","裸听→慢速→字幕→听写→跟读→无字幕复述",5,"intensive_listening","",progress.dailyAuxiliaryAttempts("intensive_listening",d)>=2,weak==ProgressStore.DIM_LISTENING?104:80,"同一句材料完成六步精听并进入句子FSRS"));int prepMist=progress.grammarMistakes("prepositions");c.add(node("preposition","🧭","介词专项","a/in/da/di/per/su 与组合介词",4,"preposition","",progress.dailyAuxiliaryAttempts("preposition",d)>=3,prepMist>1?92:64,"介词是A2→B1高频长期错误点"));int pastMist=progress.grammarMistakes("passato_prossimo")+progress.grammarMistakes("imperfetto");int pastBoost=(goal==ProgressStore.GOAL_A2||goal==ProgressStore.GOAL_B1)?20:0;c.add(node("past_tense","⏳","过去时专项","Passato prossimo vs Imperfetto · 助动词与过去分词",4,"past_tense","",progress.dailyAuxiliaryAttempts("past_tense",d)>=3,68+pastBoost+Math.min(20,pastMist*4),"A2/B1开始需要稳定区分过去完成事件和背景习惯"));int pronMist=progress.grammarMistakes("pronomi_diretti")+progress.grammarMistakes("pronomi_indiretti")+progress.grammarMistakes("ne_partitivo");int pronBoost=(goal==ProgressStore.GOAL_A2||goal==ProgressStore.GOAL_B1)?18:0;c.add(node("pronouns","🔁","代词专项","lo/la/li/le · gli/le · ci · ne",4,"pronouns","",progress.dailyAuxiliaryAttempts("pronouns",d)>=3,64+pronBoost+Math.min(20,pronMist*4),"代词是从短句走向自然表达的关键结构"));int grammarTarget=m>=60?4:2;int grammarDue=progress.dueGrammarCount();c.add(node("grammar","🧩","微语法","一个高收益语法点："+course.grammarTitle,4,"grammar",course.grammarPatternId,progress.dailyAuxiliaryAttempts("pattern",d)>=grammarTarget,70+Math.max(0,70-progress.grammarAccuracy(course.grammarPatternId))/2,"根据语法错误率选择"+(grammarDue>0?"；有 "+grammarDue+" 个语法点到期":"")));c.add(node("cloze","🧠","弱项完形","从语法弱项和弱词自动抽题",4,"cloze","",progress.dailyAuxiliaryAttempts("cloze",d)>=3,66,"把规则放回完整句子里回忆"));}
  if(m>=30){c.add(node("active_recall","🧠","主动回忆","不给选项，从中文完整想出意大利语",4,"active_recall","300",progress.dailyAuxiliaryAttempts("active_recall",d)>=3,86,"把认识的表达变成能主动说出的表达"));c.add(node("phrases","💬","高频短语","用词块直接形成日常表达",4,"phrases","",progress.dailyAuxiliaryAttempts("phrases",d)>=2,70+((goal==ProgressStore.GOAL_LIFE||goal==ProgressStore.GOAL_WORK)?18:0),"减少逐词翻译，提高开口速度"));c.add(node("family_train","🌿","词族关联","把同根词、派生词和变位连接起来",4,"family_train","",progress.dailyAuxiliaryAttempts("family_train",d)>=3,goal==ProgressStore.GOAL_B1?72:58,"用关联记忆减少孤立背词"));c.add(node("writing","✍️","写作输出","用真实生活任务把词汇和语法写出来",5,"writing","",progress.dailyAuxiliaryAttempts("writing",d)>=1,(goal==ProgressStore.GOAL_WORK||goal==ProgressStore.GOAL_A2||goal==ProgressStore.GOAL_B1)?78:52,"听说读之外补齐写作输出"));c.add(node("sentence_fsrs","🧠","句子长期复习","把高频词块作为完整表达进入间隔复习",4,"sentence_review","",progress.dailyAuxiliaryAttempts("sentence_fsrs",d)>=2,68,"减少逐词翻译，让常用句块自动化"));c.add(node("shadow","🗣","Shadowing 三遍训练","双语跟读→中文提取→裸说，录音回听并看逐词差异",7,"shadow","",progress.dailyAuxiliaryAttempts("shadowing",d)>=1,(weak==ProgressStore.DIM_SPEAKING?98:64)+(goal==ProgressStore.GOAL_LIFE?15:0),"口语弱时自动提前，并把失败句回流句子复习"));ReadingPassage rp=bestReading();if(rp!=null){ReadingComprehensibilityEngine.Score rs=new ReadingComprehensibilityEngine(repo,progress).score(rp);c.add(node("reading","📖","可理解输入",rp.level+" · 已知词 "+rs.coverage+"% · "+rp.titleZh,5,"reading",rp.id,progress.dailyAuxiliaryAttempts("reading",d)>=1,(rs.coverage>=90&&rs.coverage<=98?76:55)+((goal==ProgressStore.GOAL_A2||goal==ProgressStore.GOAL_B1)?12:0),"优先选择你已认识约90–98%词的材料"));}int verbPriority=ErrorCause.WORD_FORM.equals(topCause)||progress.grammarMistakes("verb_agreement")>0?84:54;c.add(node("verb_center","🔤","动词变位快练","现在时→近过去时→未完成过去时→将来时→条件式",4,"verb_center","",progress.dailyAuxiliaryAttempts("verb_center",d)>=3,verbPriority,"词形错误多时优先强化"));}
  if(m>=60){c.add(node("focus","🎯","专注学习","隐藏导航，连续完成一组高收益主动回忆",8,"focus_mode","",progress.dailyAuxiliaryAttempts("focus_mode",d)>=1,72,"减少页面跳转和注意力损耗"));c.add(node("pron","🗣","发音专项","双辅音、gli、gn、r 等高频难点",4,"pronunciation","",progress.dailyAuxiliaryAttempts("pronunciation",d)>=2,weak==ProgressStore.DIM_SPEAKING?82:48,"口语准确度强化"));c.add(node("mission","🎭","生活任务","完成「"+course.scenarioTitle+"」真实场景任务",5,"mission",course.scenarioId,progress.dailyAuxiliaryAttempts("mission",d)>=2,58+((goal==ProgressStore.GOAL_LIFE||goal==ProgressStore.GOAL_WORK)?20:0),"把知识转成现实表达"));c.add(node("dialogue","🗨️","情景对话","完成一轮有上下文的应答",5,"dialogue",course.scenarioId,progress.dailyAuxiliaryAttempts("dialogue",d)>=2,50,"真实轮次理解"));}
  c.sort((a,b)->{if(a.done!=b.done)return a.done?1:-1;return Integer.compare(b.priority,a.priority);});List<LearningPathNode> out=new ArrayList<>();int budget=0,max=m==5?2:(m==15?5:(m==30?7:11));for(LearningPathNode n:c){if(out.size()>=max)break;if(!n.done&&budget+n.minutes>m+3&&out.size()>=2)continue;out.add(n);if(!n.done)budget+=n.minutes;}return out;
 }
 private ReadingPassage bestReading(){List<ReadingPassage> all=ReadingRepository.get(context).all();if(all.isEmpty())return null;ReadingComprehensibilityEngine eng=new ReadingComprehensibilityEngine(repo,progress);return eng.recommended(all).get(0);}
 private LearningPathNode node(String id,String emoji,String title,String subtitle,int minutes,String action,String payload,boolean done,int priority,String reason){return new LearningPathNode(id,emoji,title,subtitle,minutes,action,payload,done,priority,reason);}
 private int causeToDim(String cause){if(ErrorCause.LISTENING_CONFUSION.equals(cause)||ErrorCause.OMISSION.equals(cause))return ProgressStore.DIM_LISTENING;if(ErrorCause.SPELLING.equals(cause)||ErrorCause.ACCENT.equals(cause))return ProgressStore.DIM_SPELLING;if(ErrorCause.PRONUNCIATION.equals(cause))return ProgressStore.DIM_SPEAKING;return ProgressStore.DIM_MEANING;}
 private String dimName(int d){return d==ProgressStore.DIM_LISTENING?"听力":(d==ProgressStore.DIM_SPELLING?"拼写":(d==ProgressStore.DIM_SPEAKING?"口语":"识义"));}
 public int completed(List<LearningPathNode> nodes){int n=0;for(LearningPathNode x:nodes)if(x.done)n++;return n;}public LearningPathNode next(List<LearningPathNode> nodes){for(LearningPathNode x:nodes)if(!x.done)return x;return null;}
}
