package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.util.*;
public class ListeningCourseFragment extends Fragment{
 private ProgressStore progress;private WordRepository words;private AudioPlayer audio;private ListeningCourseRepository repo;private Spinner level,lesson;private TextView summary,step,source,it,zh,feedback;private EditText input;private List<ListeningCourse> lessons=new ArrayList<>();private ListeningCourse course;private int index;private long started;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater inf,@Nullable ViewGroup c,@Nullable Bundle s){View v=inf.inflate(R.layout.fragment_listening_course,c,false);progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);repo=ListeningCourseRepository.get(requireContext());level=v.findViewById(R.id.spinner_lc_level);lesson=v.findViewById(R.id.spinner_lc_lesson);summary=v.findViewById(R.id.text_lc_summary);step=v.findViewById(R.id.text_lc_step);source=v.findViewById(R.id.text_lc_source);it=v.findViewById(R.id.text_lc_it);zh=v.findViewById(R.id.text_lc_zh);feedback=v.findViewById(R.id.text_lc_feedback);input=v.findViewById(R.id.edit_lc_answer);
  ArrayAdapter<String> la=new ArrayAdapter<>(requireContext(),R.layout.item_spinner_text,new String[]{"A1","A2","B1"});la.setDropDownViewResource(R.layout.item_spinner_dropdown);level.setAdapter(la);level.setSelection(progress.bestExamScore("A1")<70?0:(progress.bestExamScore("A2")<70?1:2));level.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View x,int pos,long id){reloadLessons();}public void onNothingSelected(android.widget.AdapterView<?> p){}});
  lesson.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View x,int pos,long id){if(pos>=0&&pos<lessons.size()){course=lessons.get(pos);index=0;show();}}public void onNothingSelected(android.widget.AdapterView<?> p){}});
  v.findViewById(R.id.button_lc_play).setOnClickListener(x->play(1f));v.findViewById(R.id.button_lc_slow).setOnClickListener(x->play(.76f));v.findViewById(R.id.button_lc_show_it).setOnClickListener(x->it.setVisibility(View.VISIBLE));v.findViewById(R.id.button_lc_show_zh).setOnClickListener(x->zh.setVisibility(View.VISIBLE));v.findViewById(R.id.button_lc_check).setOnClickListener(x->check());v.findViewById(R.id.button_lc_next).setOnClickListener(x->{if(course!=null){index=(index+1)%course.sentences.size();show();}});reloadLessons();return v;}
 private void reloadLessons(){String l=String.valueOf(level.getSelectedItem());lessons=repo.level(l);List<String> names=new ArrayList<>();for(ListeningCourse x:lessons)names.add(x.title+" · "+x.wpm+" WPM");ArrayAdapter<String>a=new ArrayAdapter<>(requireContext(),R.layout.item_spinner_text,names);a.setDropDownViewResource(R.layout.item_spinner_dropdown);lesson.setAdapter(a);if(!lessons.isEmpty()){course=lessons.get(0);index=0;show();}}
 private ListeningSentence current(){return course==null||course.sentences.isEmpty()?null:course.sentences.get(index%course.sentences.size());}
 private void show(){ListeningSentence s=current();if(s==null)return;it.setText(s.italian);zh.setText(s.chinese+(s.note.isEmpty()?"":"\n"+s.note));it.setVisibility(View.GONE);zh.setVisibility(View.GONE);input.setText("");input.setEnabled(true);feedback.setText("");step.setText(course.level+" · "+course.title+" · 第 "+(index+1)+" / "+course.sentences.size()+" 句");source.setText(course.subtitle+" · "+s.category);summary.setText("课程历史正确率 "+progress.auxiliaryAccuracy("listening_course")+"% · 建议：先裸听2遍，再慢速听写");started=System.currentTimeMillis();input.postDelayed(()->play(1f),250);}
 private void play(float rate){ListeningSentence s=current();if(s!=null)audio.speak(s.italian,rate);}
 private void check(){ListeningSentence s=current();if(s==null||!input.isEnabled())return;String typed=input.getText()==null?"":input.getText().toString().trim();if(typed.isEmpty()){input.setError("请写下听到的句子");return;}ErrorCauseAnalyzer.SentenceAnalysis a=ErrorCauseAnalyzer.analyzeSentence(s.italian,typed,words);boolean ok=a.score>=88;long ms=Math.max(1,System.currentTimeMillis()-started);progress.recordAuxiliaryResult("listening_course",ok,ms);SentenceFsrsRepository.recordDimension(requireContext(),"听力课程·"+course.level,s.italian,s.chinese,SentenceFsrsRepository.DIM_LISTENING,ok,a.score,null);if(!ok)for(String cause:a.causes)progress.recordErrorCause(cause,0,"listening_course",s.italian,typed,a.summary());feedback.setText((ok?"✓ ":"△ ")+"匹配度 "+a.score+"%\n"+a.summary()+"\n"+a.diff);feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));it.setVisibility(View.VISIBLE);zh.setVisibility(View.VISIBLE);input.setEnabled(false);}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
