package com.italiano2774.nativeapp;

import android.graphics.Color;import android.os.Bundle;import android.speech.tts.TextToSpeech;import android.text.*;import android.text.method.LinkMovementMethod;import android.text.style.ClickableSpan;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.appcompat.app.AlertDialog;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import java.util.*;import java.util.regex.*;

public class ReadingDetailFragment extends Fragment implements TextToSpeech.OnInitListener{
 private ReadingPassage passage;private ProgressStore progress;private WordRepository words;private TextToSpeech tts;private TextView body,translation,qText,qZh,feedback;private final List<MaterialButton> answers=new ArrayList<>();private MaterialButton next;private int qi=0,correct=0;private boolean answered=false;private long started;
 public static ReadingDetailFragment newInstance(String id){ReadingDetailFragment f=new ReadingDetailFragment();Bundle b=new Bundle();b.putString("id",id);f.setArguments(b);return f;}
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_reading_detail,c,false);String id=getArguments()==null?"":getArguments().getString("id","");passage=ReadingRepository.get(requireContext()).byId(id);if(passage==null)return v;progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());tts=new TextToSpeech(requireContext(),this);((TextView)v.findViewById(R.id.text_read_detail_level)).setText(passage.level);((TextView)v.findViewById(R.id.text_read_detail_title)).setText(passage.title);ReadingComprehensibilityEngine.Score coverage=new ReadingComprehensibilityEngine(words,progress).score(passage);String unknown=coverage.unknown.isEmpty()?"":(" · 生词示例 "+android.text.TextUtils.join("、",coverage.unknown.subList(0,Math.min(5,coverage.unknown.size()))));((TextView)v.findViewById(R.id.text_read_detail_title_zh)).setText(passage.titleZh+" · 已知词 "+coverage.coverage+"% · "+coverage.label()+" · 最好 "+progress.readingBest(passage.id)+"%"+unknown);body=v.findViewById(R.id.text_read_body);translation=v.findViewById(R.id.text_read_translation);translation.setText(passage.translation);setClickableText();v.findViewById(R.id.button_read_aloud).setOnClickListener(x->say(passage.text));v.findViewById(R.id.button_read_translation).setOnClickListener(x->{boolean show=translation.getVisibility()!=View.VISIBLE;translation.setVisibility(show?View.VISIBLE:View.GONE);((MaterialButton)x).setText(show?"隐藏中文":"显示中文");});qText=v.findViewById(R.id.text_read_question);qZh=v.findViewById(R.id.text_read_question_zh);feedback=v.findViewById(R.id.text_read_feedback);answers.add(v.findViewById(R.id.read_answer_1));answers.add(v.findViewById(R.id.read_answer_2));answers.add(v.findViewById(R.id.read_answer_3));answers.add(v.findViewById(R.id.read_answer_4));next=v.findViewById(R.id.button_read_next_question);next.setOnClickListener(x->{qi++;showQuestion();});started=System.currentTimeMillis();showQuestion();return v;}
 private void setClickableText(){SpannableString sp=new SpannableString(passage.text);Matcher m=Pattern.compile("[\\p{L}À-ÿ'’]+",Pattern.UNICODE_CASE).matcher(passage.text);while(m.find()){final String token=m.group();sp.setSpan(new ClickableSpan(){@Override public void onClick(@NonNull View widget){showWord(token);}@Override public void updateDrawState(@NonNull android.text.TextPaint ds){super.updateDrawState(ds);ds.setColor(Color.rgb(25,103,210));ds.setUnderlineText(false);}},m.start(),m.end(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);}body.setText(sp);body.setMovementMethod(LinkMovementMethod.getInstance());body.setHighlightColor(Color.TRANSPARENT);}
 private void showWord(String token){Word w=words.lookupSurface(token);String title=w==null?token:w.word;String msg;if(w==null)msg="词库里没有精确匹配。你可以把它加入个人词库，之后自己补充释义。";else{StringBuilder sb=new StringBuilder();sb.append(w.chinese);if(!w.ipa.isEmpty())sb.append("\nIPA：").append(w.ipa);if(!w.lemma.isEmpty()&&!w.lemma.equalsIgnoreCase(w.word))sb.append("\n原形：").append(w.lemma);if(!w.formInfo.isEmpty())sb.append("\n").append(w.formInfo);msg=sb.toString();}AlertDialog.Builder b=new AlertDialog.Builder(requireContext()).setTitle(title).setMessage(msg).setNegativeButton("关闭",null).setNeutralButton("加入个人词库",(d,x)->CustomLibraryRepository.add(requireContext(),"word",title,w==null?"":w.chinese,"来自阅读 · "+passage.title,id->Toast.makeText(requireContext(),"已加入个人词库",Toast.LENGTH_SHORT).show()));if(w!=null)b.setPositiveButton(progress.favorite(w.id)?"已收藏":"收藏课程词",(d,x)->{progress.setFavorite(w.id,true);Toast.makeText(requireContext(),"已收藏",Toast.LENGTH_SHORT).show();});b.show();}
 private void showQuestion(){if(qi>=passage.questions.size()){int score=passage.questions.isEmpty()?100:(int)Math.round(correct*100.0/passage.questions.size());progress.saveReadingScore(passage.id,score);progress.recordAuxiliaryResult("reading",score>=70,System.currentTimeMillis()-started);feedback.setText("完成："+correct+" / "+passage.questions.size()+" · "+score+"%"+(score>=70?" ✅":" · 建议再读一遍"));qText.setText("阅读完成");qZh.setText("最好成绩："+progress.readingBest(passage.id)+"%");for(MaterialButton b:answers)b.setVisibility(View.GONE);next.setVisibility(View.GONE);return;}answered=false;feedback.setText("");next.setVisibility(View.GONE);ReadingQuestion q=passage.questions.get(qi);qText.setText((qi+1)+". "+q.q);qZh.setText(q.zh);for(int n=0;n<answers.size();n++){MaterialButton b=answers.get(n);if(n<q.options.size()){b.setVisibility(View.VISIBLE);b.setEnabled(true);b.setText(q.options.get(n));final int idx=n;b.setOnClickListener(v->answer(idx));}else b.setVisibility(View.GONE);}}
 private void answer(int idx){if(answered)return;answered=true;ReadingQuestion q=passage.questions.get(qi);boolean ok=idx==q.answer;if(ok)correct++;for(MaterialButton b:answers)b.setEnabled(false);feedback.setText(ok?"正确 ✅":"不对。正确答案："+q.options.get(q.answer));feedback.setTextColor(getResources().getColor(ok?R.color.success:R.color.error,requireContext().getTheme()));next.setVisibility(View.VISIBLE);next.setText(qi==passage.questions.size()-1?"查看成绩":"下一题");}
 private void say(String text){if(tts!=null)tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"reading");}public void onInit(int status){if(status==TextToSpeech.SUCCESS){tts.setLanguage(Locale.ITALY);tts.setSpeechRate(0.9f);}}@Override public void onDestroyView(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroyView();}
}
