package com.italiano2774.nativeapp;
import android.content.Context;import android.os.Handler;import android.os.Looper;import java.time.LocalDate;import java.util.*;import java.util.concurrent.*;
/** v2.7 sentence-level spaced repetition with separate meaning/listening/recall/speaking dimensions. */
public final class SentenceFsrsRepository{
 public static final int DIM_MEANING=0,DIM_LISTENING=1,DIM_RECALL=2,DIM_SPEAKING=3;
 public interface Callback<T>{void done(T value);}private static final ExecutorService IO=Executors.newSingleThreadExecutor();private SentenceFsrsRepository(){}
 public static String idFor(String italian){String s=italian==null?"":italian.trim().toLowerCase(Locale.ROOT);return "s_"+Integer.toHexString(s.hashCode());}
 public static void ensure(Context c,String source,String it,String zh,Callback<SentenceProgressEntity> cb){Context app=c.getApplicationContext();IO.execute(()->{LearningStateDao dao=LearningDatabase.get(app).learningStateDao();String id=idFor(it);SentenceProgressEntity x=dao.sentence(id);if(x==null){x=new SentenceProgressEntity();x.sentenceId=id;x.source=source==null?"":source;x.italian=it==null?"":it.trim();x.chinese=zh==null?"":zh.trim();x.dueEpochDay=LocalDate.now().toEpochDay();x.updatedAt=System.currentTimeMillis();dao.upsertSentence(x);}SentenceProgressEntity out=x;if(cb!=null)new Handler(Looper.getMainLooper()).post(()->cb.done(out));});}
 public static void record(Context c,String source,String it,String zh,boolean correct,Callback<SentenceProgressEntity> cb){recordDimension(c,source,it,zh,DIM_RECALL,correct,correct?100:40,cb);}
 public static void recordDimension(Context c,String source,String it,String zh,int dim,boolean correct,int score,Callback<SentenceProgressEntity> cb){ensure(c,source,it,zh,x->{Context app=c.getApplicationContext();IO.execute(()->{LearningStateDao dao=LearningDatabase.get(app).learningStateDao();x.attempts++;if(correct)x.correct++;else x.lapses++;x.lastScore=Math.max(0,Math.min(100,score));x.lastEpochDay=LocalDate.now().toEpochDay();int old=dimension(x,dim);setDimension(x,dim,correct?Math.min(5,old+1):Math.max(0,old-1));double quality=Math.max(.25,Math.min(1.15,x.lastScore/90.0));if(correct){x.difficulty=Math.max(1.0,x.difficulty-0.14*quality);x.stability=Math.max(1.0,x.stability*(x.attempts<=2?1.75:1.48)*quality);x.intervalDays=Math.max(1,Math.min(240,(int)Math.round(x.stability)));}else{x.difficulty=Math.min(10.0,x.difficulty+0.72);x.stability=Math.max(1.0,x.stability*0.42);x.intervalDays=1;}int weakest=Math.min(Math.min(x.meaningLevel,x.listeningLevel),Math.min(x.recallLevel,x.speakingLevel));if(weakest<=1&&x.intervalDays>7)x.intervalDays=7;x.dueEpochDay=LocalDate.now().plusDays(x.intervalDays).toEpochDay();x.updatedAt=System.currentTimeMillis();dao.upsertSentence(x);LearningDatabase.log(app,"sentence_fsrs",x.sentenceId,dim,correct,0,x.source+"|score="+x.lastScore);if(cb!=null)new Handler(Looper.getMainLooper()).post(()->cb.done(x));});});}
 private static int dimension(SentenceProgressEntity x,int d){return d==DIM_LISTENING?x.listeningLevel:(d==DIM_RECALL?x.recallLevel:(d==DIM_SPEAKING?x.speakingLevel:x.meaningLevel));}
 private static void setDimension(SentenceProgressEntity x,int d,int v){if(d==DIM_LISTENING)x.listeningLevel=v;else if(d==DIM_RECALL)x.recallLevel=v;else if(d==DIM_SPEAKING)x.speakingLevel=v;else x.meaningLevel=v;}
 public static int overall(SentenceProgressEntity x){if(x==null)return 0;return (x.meaningLevel+x.listeningLevel+x.recallLevel+x.speakingLevel)/4;}
 public static void due(Context c,int limit,Callback<List<SentenceProgressEntity>> cb){Context app=c.getApplicationContext();IO.execute(()->{List<SentenceProgressEntity>x=LearningDatabase.get(app).learningStateDao().dueSentences(LocalDate.now().toEpochDay(),limit);new Handler(Looper.getMainLooper()).post(()->cb.done(x));});}
 public static void seedPhrases(Context c,Callback<Integer> cb){Context app=c.getApplicationContext();IO.execute(()->{LearningStateDao dao=LearningDatabase.get(app).learningStateDao();if(dao.sentenceCount()<100){int n=0;for(CoreSentence p:CoreSentenceRepository.get(app).all()){if(n>=180)break;String id=idFor(p.italian);if(dao.sentence(id)==null){SentenceProgressEntity x=new SentenceProgressEntity();x.sentenceId=id;x.source="核心句";x.italian=p.italian;x.chinese=p.chinese;x.dueEpochDay=LocalDate.now().toEpochDay();x.updatedAt=System.currentTimeMillis();dao.upsertSentence(x);n++;}}}int count=dao.sentenceCount();if(cb!=null)new Handler(Looper.getMainLooper()).post(()->cb.done(count));});}
}
