package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import java.util.*;
public class SentenceReviewFragment extends Fragment{
 private List<SentenceProgressEntity> items=new ArrayList<>();private int index=0;private TextView source,it,zh,stats;private View grade;private AudioPlayer audio;private ProgressStore progress;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_sentence_review,c,false);progress=new ProgressStore(requireContext());audio=new AudioPlayer(requireContext(),progress);source=v.findViewById(R.id.text_sentence_source);it=v.findViewById(R.id.text_sentence_it);zh=v.findViewById(R.id.text_sentence_zh);stats=v.findViewById(R.id.text_sentence_review_stats);grade=v.findViewById(R.id.group_sentence_grade);v.findViewById(R.id.button_sentence_review_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_sentence_audio).setOnClickListener(x->{if(!items.isEmpty())audio.speak(items.get(index).italian,.92f);});v.findViewById(R.id.button_sentence_reveal).setOnClickListener(x->{zh.setVisibility(View.VISIBLE);grade.setVisibility(View.VISIBLE);x.setVisibility(View.GONE);});v.findViewById(R.id.button_sentence_again).setOnClickListener(x->grade(false));v.findViewById(R.id.button_sentence_good).setOnClickListener(x->grade(true));SentenceFsrsRepository.seedPhrases(requireContext(),n->load());return v;}
 private void load(){SentenceFsrsRepository.due(requireContext(),40,x->{items=x;index=0;render();});}
 private void render(){View reveal=getView()==null?null:getView().findViewById(R.id.button_sentence_reveal);if(items.isEmpty()){source.setText("今天没有到期句子");it.setText("🎉 句子长期复习已清空");zh.setText("去高频短语中复习任意表达，它会自动进入句子FSRS。");zh.setVisibility(View.VISIBLE);grade.setVisibility(View.GONE);if(reveal!=null)reveal.setVisibility(View.GONE);stats.setText("到期 0 · 句子FSRS会根据记忆稳定度自动安排下一次复习");return;}SentenceProgressEntity x=items.get(index);source.setText(x.source.isEmpty()?"句子FSRS":x.source);it.setText(x.italian);zh.setText(x.chinese);zh.setVisibility(View.GONE);grade.setVisibility(View.GONE);if(reveal!=null)reveal.setVisibility(View.VISIBLE);stats.setText("到期 "+items.size()+" · 当前 "+(index+1)+" / "+items.size()+" · 间隔 "+x.intervalDays+"天\n四维：理解 "+x.meaningLevel+" · 听力 "+x.listeningLevel+" · 主动回忆 "+x.recallLevel+" · 口语 "+x.speakingLevel+" · 遗忘 "+x.lapses+"次");}
 private void grade(boolean correct){if(items.isEmpty())return;SentenceProgressEntity x=items.get(index);SentenceFsrsRepository.record(requireContext(),x.source,x.italian,x.chinese,correct,y->{progress.recordAuxiliaryResult("sentence_fsrs",correct,0);items.remove(index);if(index>=items.size())index=0;render();});}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
