package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.util.*;
public class SentenceDictationFragment extends Fragment{
 private ProgressStore progress;private WordRepository repo;private AudioPlayer audio;private List<SentenceDictationItem> session;private int index=0,correctCount=0;private long started;private TextView stats,source,score,cause,diff,answer,zh;private EditText input;private View feedback,next;private SentenceDictationItem current;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_sentence_dictation,c,false);progress=new ProgressStore(requireContext());repo=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);session=new SentenceDictationRepository(requireContext()).session(progress.sessionMinutes()>=30?10:6);stats=v.findViewById(R.id.text_sd_stats);source=v.findViewById(R.id.text_sd_source);score=v.findViewById(R.id.text_sd_score);cause=v.findViewById(R.id.text_sd_cause);diff=v.findViewById(R.id.text_sd_diff);answer=v.findViewById(R.id.text_sd_answer);zh=v.findViewById(R.id.text_sd_zh);input=v.findViewById(R.id.edit_sd_answer);feedback=v.findViewById(R.id.panel_sd_feedback);next=v.findViewById(R.id.button_sd_next);v.findViewById(R.id.button_sd_play).setOnClickListener(x->play(0.92f));v.findViewById(R.id.button_sd_slow).setOnClickListener(x->play(0.72f));v.findViewById(R.id.button_sd_submit).setOnClickListener(x->submit());next.setOnClickListener(x->{index++;show();});input.setOnEditorActionListener((tv,a,e)->{if(a==EditorInfo.IME_ACTION_DONE){submit();return true;}return false;});show();return v;}
 private void show(){feedback.setVisibility(View.GONE);next.setVisibility(View.GONE);input.setText("");input.setEnabled(true);if(index>=session.size()){source.setText("本轮完成");input.setVisibility(View.GONE);stats.setText("完成 "+session.size()+" 句 · 完整正确 "+correctCount+" · "+(session.isEmpty()?0:(correctCount*100/session.size()))+"%");return;}current=session.get(index);source.setText(current.source);stats.setText("第 "+(index+1)+" / "+session.size()+" 句 · 本轮完整正确 "+correctCount);started=System.currentTimeMillis();input.postDelayed(()->play(0.92f),220);}
 private void play(float rate){if(current!=null)audio.speak(current.italian,rate);}
 private void submit(){if(current==null||!input.isEnabled())return;String typed=input.getText()==null?"":input.getText().toString().trim();if(typed.isEmpty()){input.setError("请先输入你听到的句子");return;}long ms=System.currentTimeMillis()-started;ErrorCauseAnalyzer.SentenceAnalysis a=ErrorCauseAnalyzer.analyzeSentence(current.italian,typed,repo);boolean ok=a.score>=94&&!a.causes.contains(ErrorCause.ACCENT);progress.recordAuxiliaryResult("sentence_dictation",ok,ms);if(ok){correctCount++;String top=progress.topErrorCause();if(ErrorCause.WORD_ORDER.equals(top)||ErrorCause.OMISSION.equals(top)||ErrorCause.SPELLING.equals(top)||ErrorCause.LISTENING_CONFUSION.equals(top))progress.markAuxiliaryCompletion("error_repair");}else{for(String c:a.causes)progress.recordErrorCause(c,0,"sentence_dictation",current.italian,typed,a.summary());markWeakWords(current.italian,typed);}score.setText((ok?"✓ ":"△ ")+"内容匹配度 "+a.score+"%");score.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.text_primary));cause.setText(ok?"句子基本完整":("主要问题："+ErrorCause.label(a.primaryCause())+" · "+a.summary()));cause.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));diff.setText(a.diff);answer.setText(current.italian);zh.setText(current.chinese+(current.note.isEmpty()?"":"\n提示："+current.note));feedback.setVisibility(View.VISIBLE);next.setVisibility(View.VISIBLE);input.setEnabled(false);}
 private void markWeakWords(String expected,String actual){Set<String> got=new HashSet<>(Arrays.asList(ErrorCauseAnalyzer.basic(actual).split(" ")));int marked=0;for(String raw:ErrorCauseAnalyzer.basic(expected).split(" ")){if(raw.length()<3||got.contains(raw))continue;Word w=repo.lookupSurface(raw);if(w!=null){progress.recordDimensionResults(w.id,new int[]{ProgressStore.DIM_LISTENING,ProgressStore.DIM_SPELLING},false,0);if(++marked>=3)break;}}}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
