package com.italiano2774.nativeapp;

import android.app.AlertDialog;import android.app.DatePickerDialog;import android.app.TimePickerDialog;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import com.google.android.material.switchmaterial.SwitchMaterial;import java.time.LocalDate;import java.util.Arrays;import java.util.concurrent.ExecutorService;import java.util.concurrent.Executors;

public class SettingsFragment extends Fragment {
    private static final ExecutorService STATS_EXECUTOR=Executors.newSingleThreadExecutor();
    private ProgressStore progress;private WordRepository repo;private Button dateButton,timeButton;private Spinner perDay,sessionMinutes,pronMode,retention,vocabRoute,learningGoal,audioSpeed,fontSize;private SwitchMaterial original,reminder,simpleHome;private LocalDate selectedDate;private int reminderHour,reminderMinute;
    @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){
        View v=i.inflate(R.layout.fragment_settings,c,false);progress=new ProgressStore(requireContext());repo=WordRepository.get(requireContext());selectedDate=progress.startDate();reminderHour=progress.reminderHour();reminderMinute=progress.reminderMinute();
        dateButton=v.findViewById(R.id.button_start_date);timeButton=v.findViewById(R.id.button_reminder_time);perDay=v.findViewById(R.id.spinner_per_day);sessionMinutes=v.findViewById(R.id.spinner_session_minutes);pronMode=v.findViewById(R.id.spinner_pronunciation_mode);retention=v.findViewById(R.id.spinner_retention);vocabRoute=v.findViewById(R.id.spinner_vocab_route);learningGoal=v.findViewById(R.id.spinner_learning_goal);audioSpeed=v.findViewById(R.id.spinner_audio_speed);fontSize=v.findViewById(R.id.spinner_font_size);original=v.findViewById(R.id.switch_original_audio);reminder=v.findViewById(R.id.switch_reminder);simpleHome=v.findViewById(R.id.switch_simple_home);dateButton.setText(selectedDate.toString());updateReminderText();dateButton.setOnClickListener(x->pickDate());timeButton.setOnClickListener(x->pickTime());
        Integer[] opts={10,20,30,50};ArrayAdapter<Integer>a=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,opts);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);perDay.setAdapter(a);int currentWords=progress.perDay(),idx=Arrays.asList(opts).indexOf(currentWords);if(idx<0)idx=currentWords<=15?0:(currentWords<=25?1:(currentWords<=40?2:3));perDay.setSelection(idx);
        String[] routes={"核心1000词 · 先快速开口","B1核心1600词 · 推荐","完整2774词 · 全课程"};ArrayAdapter<String> vra=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,routes);vra.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);vocabRoute.setAdapter(vra);int vr=progress.vocabularyRouteLimit();vocabRoute.setSelection(vr==ProgressStore.ROUTE_1000?0:(vr==ProgressStore.ROUTE_1600?1:2));
        String[] goals={"🇮🇹 意大利生活","💼 工作交流","📝 A2能力","🎓 B1能力","🌍 综合学习"};ArrayAdapter<String> ga=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,goals);ga.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);learningGoal.setAdapter(ga);learningGoal.setSelection(progress.learningGoal());
        Integer[] mins={10,20,30,45,60};ArrayAdapter<Integer>ma=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,mins);ma.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);sessionMinutes.setAdapter(ma);int mi=Arrays.asList(mins).indexOf(progress.sessionMinutes());sessionMinutes.setSelection(mi<0?1:mi);
        String[] ret={"85% · 更少复习","90% · 推荐","95% · 更牢固"};ArrayAdapter<String>ra=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,ret);ra.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);retention.setAdapter(ra);double rv=progress.desiredRetention();retention.setSelection(rv>=0.94?2:(rv<0.88?0:1));
        String[] pron={"总是显示","自动隐藏（推荐）","点击/显示答案后显示","永不显示"};ArrayAdapter<String>pa=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,pron);pa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);pronMode.setAdapter(pa);pronMode.setSelection(progress.pronunciationMode());
        String[] speeds={"0.75× · 精听","1.0× · 正常","1.15× · 提速"};ArrayAdapter<String>sa=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,speeds);sa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);audioSpeed.setAdapter(sa);audioSpeed.setSelection(progress.audioSpeedMode());
        String[] fonts={"小","标准（推荐）","大","超大"};ArrayAdapter<String>fa=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,fonts);fa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);fontSize.setAdapter(fa);fontSize.setSelection(progress.fontScaleMode());
        original.setChecked(progress.preferOriginalAudio());reminder.setChecked(progress.reminderEnabled());simpleHome.setChecked(progress.homeSimpleMode());LinearLayout advanced=v.findViewById(R.id.container_settings_advanced);Button advancedButton=v.findViewById(R.id.button_settings_advanced);advancedButton.setOnClickListener(x->{boolean show=advanced.getVisibility()!=View.VISIBLE;advanced.setVisibility(show?View.VISIBLE:View.GONE);advancedButton.setText(show?"收起高级设置 ▴":"高级设置 ▾");});v.findViewById(R.id.button_placement_settings).setOnClickListener(x->((MainActivity)requireActivity()).openPlacementTest());
        v.findViewById(R.id.button_save_settings).setOnClickListener(x->{int oldFont=progress.fontScaleMode();progress.setStartDate(selectedDate);progress.setPerDay((Integer)perDay.getSelectedItem());progress.setVocabularyRouteLimit(vocabRoute.getSelectedItemPosition()==0?ProgressStore.ROUTE_1000:(vocabRoute.getSelectedItemPosition()==1?ProgressStore.ROUTE_1600:ProgressStore.ROUTE_2774));progress.setLearningGoal(learningGoal.getSelectedItemPosition());progress.setSessionMinutes((Integer)sessionMinutes.getSelectedItem());progress.setDesiredRetention(retention.getSelectedItemPosition()==0?0.85:(retention.getSelectedItemPosition()==2?0.95:0.90));progress.setPronunciationMode(pronMode.getSelectedItemPosition());progress.setAudioSpeedMode(audioSpeed.getSelectedItemPosition());progress.setFontScaleMode(fontSize.getSelectedItemPosition());progress.setPreferOriginalAudio(original.isChecked());progress.setHomeSimpleMode(simpleHome.isChecked());progress.setReminderEnabled(reminder.isChecked());progress.setReminderTime(reminderHour,reminderMinute);if(reminder.isChecked()){((MainActivity)requireActivity()).requestNotificationPermissionIfNeeded();ReminderScheduler.schedule(requireContext(),reminderHour,reminderMinute);}else ReminderScheduler.cancel(requireContext());Toast.makeText(requireContext(),"设置已保存 · 首页模式会在下次打开首页时生效",Toast.LENGTH_SHORT).show();if(oldFont!=progress.fontScaleMode())v.postDelayed(()->{if(isAdded())requireActivity().recreate();},120);else refreshStats(v);});
        v.findViewById(R.id.button_export).setOnClickListener(x->((MainActivity)requireActivity()).exportProgress());v.findViewById(R.id.button_import).setOnClickListener(x->((MainActivity)requireActivity()).importProgress());v.findViewById(R.id.button_local_backup).setOnClickListener(x->{((MainActivity)requireActivity()).createLocalBackup();v.postDelayed(()->refreshStats(v),700);});v.findViewById(R.id.button_database_health).setOnClickListener(x->((MainActivity)requireActivity()).openDatabaseHealth());IssueReportStore issueStore=new IssueReportStore(requireContext());Button issueButton=v.findViewById(R.id.button_issue_reports);issueButton.setText("待检查内容（"+issueStore.count()+"）");issueButton.setOnClickListener(x->showIssueReports(issueStore,issueButton));v.findViewById(R.id.button_restore_local).setOnClickListener(x->new AlertDialog.Builder(requireContext()).setTitle("恢复最近本地备份？").setMessage("当前学习进度将被最近一次本地备份覆盖。建议如有需要先导出JSON。 ").setNegativeButton("取消",null).setPositiveButton("恢复",(d,w)->((MainActivity)requireActivity()).restoreLatestLocalBackup()).show());v.findViewById(R.id.button_reset).setOnClickListener(x->new AlertDialog.Builder(requireContext()).setTitle("清空学习进度？").setMessage("掌握度、四维进度、FSRS记忆状态、错词本、易混记录、阶段自测成绩、详细学习事件和收藏会清空；学习计划、提醒与目标记忆保持率设置保留。").setNegativeButton("取消",null).setPositiveButton("清空",(d,w)->{progress.reset();refreshStats(v);Toast.makeText(requireContext(),"已清空",Toast.LENGTH_SHORT).show();}).show());refreshStats(v);return v;
    }
    private void showIssueReports(IssueReportStore store,Button button){
        String text=store.displayText();new AlertDialog.Builder(requireContext()).setTitle("待检查内容 · "+store.count()+"条").setMessage(text).setNegativeButton("关闭",null).setNeutralButton("复制全部",(d,w)->{android.content.ClipboardManager cm=(android.content.ClipboardManager)requireContext().getSystemService(android.content.Context.CLIPBOARD_SERVICE);if(cm!=null)cm.setPrimaryClip(android.content.ClipData.newPlainText("终学意语待检查清单",store.exportText()));Toast.makeText(requireContext(),"已复制待检查清单",Toast.LENGTH_SHORT).show();}).setPositiveButton("清空",(d,w)->new AlertDialog.Builder(requireContext()).setTitle("清空待检查清单？").setMessage("只会清除你标记的问题，不影响学习进度。").setNegativeButton("取消",null).setPositiveButton("清空",(d2,w2)->{store.clear();button.setText("待检查内容（0）");Toast.makeText(requireContext(),"已清空待检查清单",Toast.LENGTH_SHORT).show();}).show()).show();
    }
    private void pickDate(){DatePickerDialog d=new DatePickerDialog(requireContext(),(view,y,m,day)->{selectedDate=LocalDate.of(y,m+1,day);dateButton.setText(selectedDate.toString());},selectedDate.getYear(),selectedDate.getMonthValue()-1,selectedDate.getDayOfMonth());d.show();}
    private void pickTime(){TimePickerDialog d=new TimePickerDialog(requireContext(),(view,h,m)->{reminderHour=h;reminderMinute=m;updateReminderText();},reminderHour,reminderMinute,true);d.show();}
    private void updateReminderText(){if(timeButton!=null)timeButton.setText(String.format("提醒时间  %02d:%02d",reminderHour,reminderMinute));}
    private void refreshStats(View v){
        TextView t=v.findViewById(R.id.text_stats),ps=v.findViewById(R.id.text_placement_status),backup=v.findViewById(R.id.text_local_backup);backup.setText(LocalBackupManager.latestLabel(requireContext()));ps.setText(progress.placementCompleted()?"上次测试保守跳过约 "+progress.placementKnownEstimate()+" 个已会词。":"尚未进行入门测试。新用户建议先测试，可减少重复学习。");t.setText("正在后台统计学习数据…");
        android.content.Context app=requireContext().getApplicationContext();STATS_EXECUTOR.execute(()->{try{ProgressStore.DashboardStats ds=progress.dashboardStats(repo.all(),LocalDate.now());String text="词汇路线："+progress.vocabularyRouteLabel()+" · "+ds.routeIntroduced+" / "+progress.vocabularyRouteLimit()+" · 目标："+progress.learningGoalLabel()+"\n"+ds.reviewPressureAdvice+"\n已接触："+ds.totalIntroduced+" / "+repo.size()+"\nB1可用（四维门槛）："+progress.b1Count(repo.all())+" / 1600\n完全掌握（综合5级）："+progress.strongCount(repo.all())+"\n今日待复习："+ds.due+" · 建议新词："+ds.newQuota+"\n最近7天正确率："+ds.sevenDayAccuracy+"% · FSRS目标保持率："+(int)Math.round(progress.desiredRetention()*100)+"%\n错词本："+ds.wrong+" · 顽固词："+ds.stubborn+"\n四维平均：识义 "+ds.learnedDimensionPct[0]+"% · 听力 "+ds.learnedDimensionPct[1]+"% · 拼写 "+ds.learnedDimensionPct[2]+"% · 口语 "+ds.learnedDimensionPct[3]+"%\n阶段自测最好：A1 "+progress.bestExamScore("A1")+"% · A2 "+progress.bestExamScore("A2")+"% · B1 "+progress.bestExamScore("B1")+"%\n练习总正确率："+progress.totalAccuracy(repo.all())+"% · 连续学习："+progress.activityStreak()+" 天";if(isAdded())requireActivity().runOnUiThread(()->{if(getView()!=null)t.setText(text);});}catch(Exception e){LocalErrorLog.write(app,"Settings stats",e);if(isAdded())requireActivity().runOnUiThread(()->{if(getView()!=null)t.setText("统计暂时无法刷新，学习数据本身不会受影响。");});}});
    }
}
