package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import java.text.Normalizer;import java.util.Locale;
public class SmartClozeFragment extends Fragment{
 private ProgressStore progress;private WordRepository repo;private SmartClozeEngine engine;private AudioPlayer audio;private TextView stats,source,prompt,zh,feedback,explanation;private EditText input;private View answerPanel;private ClozeItem current;private long started;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_smart_cloze,c,false);progress=new ProgressStore(requireContext());repo=WordRepository.get(requireContext());engine=new SmartClozeEngine(requireContext(),repo,progress);audio=new AudioPlayer(requireContext(),progress);stats=v.findViewById(R.id.text_cloze_stats);source=v.findViewById(R.id.text_cloze_source);prompt=v.findViewById(R.id.text_cloze_prompt);zh=v.findViewById(R.id.text_cloze_zh);feedback=v.findViewById(R.id.text_cloze_feedback);explanation=v.findViewById(R.id.text_cloze_explanation);input=v.findViewById(R.id.edit_cloze_answer);answerPanel=v.findViewById(R.id.cloze_answer_panel);v.findViewById(R.id.button_cloze_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_cloze_check).setOnClickListener(x->grade());v.findViewById(R.id.button_cloze_next).setOnClickListener(x->showNext());v.findViewById(R.id.button_cloze_audio).setOnClickListener(x->{if(current!=null)audio.speak(current.italian);});input.setOnEditorActionListener((tv,a,e)->{if(a==EditorInfo.IME_ACTION_DONE){grade();return true;}return false;});showNext();return v;}
 private void showNext(){current=engine.next();if(current==null)return;source.setText(current.source);prompt.setText(current.prompt);zh.setText(current.chinese);input.setText("");input.setEnabled(true);feedback.setText("");answerPanel.setVisibility(View.GONE);started=System.currentTimeMillis();refreshStats();}
 private void grade(){if(current==null||!input.isEnabled())return;String actual=input.getText()==null?"":input.getText().toString();boolean ok=norm(actual).equals(norm(current.answer));long ms=Math.max(1,System.currentTimeMillis()-started);progress.recordAuxiliaryResult("cloze",ok,ms);if(!current.patternId.isEmpty())progress.recordGrammarResult(current.patternId,ok,ms);if(current.wordId>0)progress.recordDimensionResult(current.wordId,ProgressStore.DIM_SPELLING,ok,ms);if(!ok){String cause=current.patternId.isEmpty()?ErrorCause.SPELLING:ErrorCause.GRAMMAR;progress.recordErrorCause(cause,current.wordId,"cloze",current.answer,actual,current.source);}feedback.setText(ok?"✓ 正确":"✗ 正确答案："+current.answer);feedback.setTextColor(ContextCompat.getColor(requireContext(),ok?R.color.success:R.color.error));explanation.setText(current.italian+"\n"+current.chinese+"\n\n"+current.explanation);answerPanel.setVisibility(View.VISIBLE);input.setEnabled(false);audio.speak(current.italian);refreshStats();}
 private void refreshStats(){stats.setText("本地自适应完形 "+progress.auxiliaryAttempts("cloze")+"题 · 正确率 "+progress.auxiliaryAccuracy("cloze")+"% · 优先抽取你的语法弱项和弱词");}private String norm(String s){if(s==null)return"";return Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ITALIAN).replace('’','\'').replaceAll("[^a-z0-9' ]"," ").replaceAll("\\s+"," ").trim();}@Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
