package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import java.util.*;
public class StubbornWordsFragment extends Fragment{
 private ProgressStore progress;private WordRepository repo;private AudioPlayer audio;private List<Word> pool;private int index=0;private Word current;private TextView stats,prompt,word,answer,example,reason;private long started;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_stubborn_words,c,false);progress=new ProgressStore(requireContext());repo=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);pool=repo.stubbornWords(progress);stats=v.findViewById(R.id.text_stubborn_stats);prompt=v.findViewById(R.id.text_stubborn_prompt);word=v.findViewById(R.id.text_stubborn_word);answer=v.findViewById(R.id.text_stubborn_answer);example=v.findViewById(R.id.text_stubborn_example);reason=v.findViewById(R.id.text_stubborn_reason);v.findViewById(R.id.button_stubborn_reveal).setOnClickListener(x->{answer.setVisibility(View.VISIBLE);example.setVisibility(View.VISIBLE);});v.findViewById(R.id.button_stubborn_audio).setOnClickListener(x->{if(current!=null)audio.play(current);});v.findViewById(R.id.button_stubborn_example_audio).setOnClickListener(x->{if(current!=null&&ExampleQuality.isUsable(current))audio.speak(current.example,.9f);});v.findViewById(R.id.button_stubborn_0).setOnClickListener(x->rate(0));v.findViewById(R.id.button_stubborn_1).setOnClickListener(x->rate(1));v.findViewById(R.id.button_stubborn_2).setOnClickListener(x->rate(2));v.findViewById(R.id.button_stubborn_3).setOnClickListener(x->rate(3));show();return v;}
 private void show(){if(pool.isEmpty()||index>=pool.size()){stats.setText("目前没有顽固词 🎉");prompt.setText("系统会把反复出错、长期低正确率的词自动放到这里。");word.setText("");answer.setVisibility(View.GONE);example.setVisibility(View.GONE);return;}current=pool.get(index);int mode=index%4;stats.setText("顽固词 "+(index+1)+" / "+pool.size()+" · 全库当前 "+progress.stubbornCount(repo.all())+" 个");answer.setText(current.word+" · "+current.chinese+(current.ipa.isEmpty()?"":"\n"+current.ipa));example.setText(ExampleQuality.isUsable(current)?current.example+"\n"+current.exampleZh:"暂无可靠例句，先练词义和发音");answer.setVisibility(View.GONE);example.setVisibility(View.GONE);reason.setText("错 "+progress.wrongCount(current.id)+" 次 · 正确率 "+accuracy(current)+"% · 当前最弱："+progress.weakestDimensionName(current.id));if(mode==0){prompt.setText("① 先回忆词义，再显示答案");word.setText(current.word);}else if(mode==1){prompt.setText("② 先听发音，再回忆单词和词义");word.setText("🔊 只听不看");audio.play(current);}else if(mode==2){prompt.setText("③ 看中文，主动回忆意大利语");word.setText(current.chinese);}else{prompt.setText("④ 在例句语境中回忆目标词");String ex=!ExampleQuality.isUsable(current)?current.chinese:current.example.replaceAll("(?i)\\b"+java.util.regex.Pattern.quote(current.word)+"\\b","____");word.setText(ex);}started=System.currentTimeMillis();}
 private int accuracy(Word w){int a=progress.attempts(w.id);return a==0?0:(int)Math.round(progress.correctAnswers(w.id)*100.0/a);}
 private void rate(int r){if(current==null)return;progress.recordStudyRating(current.id,r);progress.recordAuxiliaryResult("stubborn",r>=2,System.currentTimeMillis()-started);index++;show();}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
