package com.italiano2774.nativeapp;
import java.util.*;
/** Offline Italian conjugation helper for the learner's verb center. High-frequency irregulars are curated; other verbs use regular rules. */
public final class VerbConjugator{
 private VerbConjugator(){}
 public static final String PRESENT="presente",PASSATO="passato_prossimo",IMPERFETTO="imperfetto",FUTURO="futuro",CONDIZIONALE="condizionale";
 private static final String[] PERSONS={"io","tu","lui/lei","noi","voi","loro"};
 private static final Map<String,String[]> PRESENT_IRR=new HashMap<>();private static final Map<String,String[]> IMPERFECT_IRR=new HashMap<>();private static final Map<String,String> FUTURE_STEM=new HashMap<>();private static final Map<String,String> PARTICIPLE=new HashMap<>();private static final Set<String> ESSERE_AUX=new HashSet<>();
 static{
  p("essere","sono","sei","è","siamo","siete","sono");p("avere","ho","hai","ha","abbiamo","avete","hanno");p("andare","vado","vai","va","andiamo","andate","vanno");p("fare","faccio","fai","fa","facciamo","fate","fanno");p("dare","do","dai","dà","diamo","date","danno");p("stare","sto","stai","sta","stiamo","state","stanno");p("dire","dico","dici","dice","diciamo","dite","dicono");p("venire","vengo","vieni","viene","veniamo","venite","vengono");p("potere","posso","puoi","può","possiamo","potete","possono");p("volere","voglio","vuoi","vuole","vogliamo","volete","vogliono");p("dovere","devo","devi","deve","dobbiamo","dovete","devono");p("sapere","so","sai","sa","sappiamo","sapete","sanno");p("uscire","esco","esci","esce","usciamo","uscite","escono");p("bere","bevo","bevi","beve","beviamo","bevete","bevono");p("tenere","tengo","tieni","tiene","teniamo","tenete","tengono");p("rimanere","rimango","rimani","rimane","rimaniamo","rimanete","rimangono");p("scegliere","scelgo","scegli","sceglie","scegliamo","scegliete","scelgono");p("salire","salgo","sali","sale","saliamo","salite","salgono");p("morire","muoio","muori","muore","moriamo","morite","muoiono");p("sedere","siedo","siedi","siede","sediamo","sedete","siedono");p("piacere","piaccio","piaci","piace","piacciamo","piacete","piacciono");p("togliere","tolgo","togli","toglie","togliamo","togliete","tolgono");p("porre","pongo","poni","pone","poniamo","ponete","pongono");p("tradurre","traduco","traduci","traduce","traduciamo","traducete","traducono");p("condurre","conduco","conduci","conduce","conduciamo","conducete","conducono");p("produrre","produco","produci","produce","produciamo","producete","producono");p("riuscire","riesco","riesci","riesce","riusciamo","riuscite","riescono");
  IMPERFECT_IRR.put("essere",new String[]{"ero","eri","era","eravamo","eravate","erano"});
  String[][] fs={{"essere","sar"},{"avere","avr"},{"andare","andr"},{"fare","far"},{"dare","dar"},{"stare","star"},{"venire","verr"},{"tenere","terr"},{"rimanere","rimarr"},{"volere","vorr"},{"potere","potr"},{"dovere","dovr"},{"sapere","sapr"},{"vedere","vedr"},{"vivere","vivr"},{"bere","berr"},{"cadere","cadr"},{"valere","varr"},{"tradurre","tradurr"},{"condurre","condurr"},{"produrre","produrr"},{"porre","porr"}};for(String[]x:fs)FUTURE_STEM.put(x[0],x[1]);
  String[][] pp={{"essere","stato"},{"avere","avuto"},{"fare","fatto"},{"dire","detto"},{"vedere","visto"},{"prendere","preso"},{"scrivere","scritto"},{"leggere","letto"},{"bere","bevuto"},{"venire","venuto"},{"rimanere","rimasto"},{"nascere","nato"},{"morire","morto"},{"chiedere","chiesto"},{"rispondere","risposto"},{"mettere","messo"},{"scegliere","scelto"},{"aprire","aperto"},{"chiudere","chiuso"},{"perdere","perso"},{"correre","corso"},{"vivere","vissuto"},{"rompere","rotto"},{"offrire","offerto"},{"scendere","sceso"},{"accendere","acceso"},{"spegnere","spento"},{"decidere","deciso"},{"conoscere","conosciuto"},{"sapere","saputo"},{"volere","voluto"},{"potere","potuto"},{"dovere","dovuto"},{"piacere","piaciuto"},{"uscire","uscito"},{"salire","salito"},{"tradurre","tradotto"},{"condurre","condotto"},{"produrre","prodotto"},{"togliere","tolto"},{"porre","posto"}};for(String[]x:pp)PARTICIPLE.put(x[0],x[1]);
  ESSERE_AUX.addAll(Arrays.asList("essere","andare","arrivare","partire","venire","entrare","uscire","nascere","morire","restare","rimanere","tornare","diventare","cadere","scendere"));
 }
 private static void p(String l,String...f){PRESENT_IRR.put(l,f);}
 public static String[] persons(){return PERSONS.clone();}
 public static String[] tenseIds(){return new String[]{PRESENT,PASSATO,IMPERFETTO,FUTURO,CONDIZIONALE};}
 public static String label(String tense){switch(tense){case PASSATO:return"近过去时 Passato prossimo · A2";case IMPERFETTO:return"未完成过去时 Imperfetto · A2";case FUTURO:return"简单将来时 Futuro semplice · B1";case CONDIZIONALE:return"现在条件式 Condizionale · B1";default:return"直陈式现在时 Presente · A1";}}
 public static String note(String lemma,String tense){if(PASSATO.equals(tense)&&ESSERE_AUX.contains(lemma))return"使用 essere 作助动词；过去分词要随主语性数变化。";if(PASSATO.equals(tense))return"使用 avere 作助动词。";if(IMPERFETTO.equals(tense))return"常用于过去的背景、习惯或持续状态。";if(FUTURO.equals(tense))return"用于将来计划、预测，也可表示推测。";if(CONDIZIONALE.equals(tense))return"常用于礼貌请求、愿望和假设。";return"A1优先掌握现在时，再逐步扩展过去和将来。";}
 public static String[] forms(String lemma,String tense){lemma=norm(lemma);if(!isInf(lemma))return null;switch(tense){case PASSATO:return passato(lemma);case IMPERFETTO:return imperfetto(lemma);case FUTURO:return futuro(lemma);case CONDIZIONALE:return condizionale(lemma);default:return presente(lemma);}}
 public static String[] presente(String l){l=norm(l);if(PRESENT_IRR.containsKey(l))return PRESENT_IRR.get(l).clone();if(l.endsWith("are"))return regularAre(l);if(l.endsWith("ere")){String s=l.substring(0,l.length()-3);return new String[]{s+"o",s+"i",s+"e",s+"iamo",s+"ete",s+"ono"};}if(l.endsWith("ire")){String s=l.substring(0,l.length()-3);boolean isc=isIsc(l);return isc?new String[]{s+"isco",s+"isci",s+"isce",s+"iamo",s+"ite",s+"iscono"}:new String[]{s+"o",s+"i",s+"e",s+"iamo",s+"ite",s+"ono"};}return null;}
 private static String[] regularAre(String l){String s=l.substring(0,l.length()-3);if(l.endsWith("care")||l.endsWith("gare"))return new String[]{s+"o",s+"hi",s+"a",s+"hiamo",s+"ate",s+"ano"};if(s.endsWith("i"))return new String[]{s+"o",s,s+"a",s+"amo",s+"ate",s+"ano"};return new String[]{s+"o",s+"i",s+"a",s+"iamo",s+"ate",s+"ano"};}
 private static boolean isIsc(String l){return Arrays.asList("capire","finire","preferire","pulire","spedire","costruire","restituire","suggerire","proibire","definire","guarire","obbedire","chiarire","impedire","dimagrire","unire","ferire","fallire").contains(l);}
 private static String[] imperfetto(String l){if(IMPERFECT_IRR.containsKey(l))return IMPERFECT_IRR.get(l).clone();String base=l.substring(0,l.length()-2);return new String[]{base+"vo",base+"vi",base+"va",base+"vamo",base+"vate",base+"vano"};}
 private static String stemFuture(String l){String x=FUTURE_STEM.get(l);if(x!=null)return x;if(l.endsWith("are")){String root=l.substring(0,l.length()-3);if(l.endsWith("care")||l.endsWith("gare"))return root+"her";if(l.endsWith("ciare")||l.endsWith("giare"))return l.substring(0,l.length()-4)+"er";return root+"er";}if(l.endsWith("ere"))return l.substring(0,l.length()-3)+"er";if(l.endsWith("ire"))return l.substring(0,l.length()-3)+"ir";return l;}
 private static String[] futuro(String l){String s=stemFuture(l);return new String[]{s+"ò",s+"ai",s+"à",s+"emo",s+"ete",s+"anno"};}
 private static String[] condizionale(String l){String s=stemFuture(l);return new String[]{s+"ei",s+"esti",s+"ebbe",s+"emmo",s+"este",s+"ebbero"};}
 private static String participle(String l){String x=PARTICIPLE.get(l);if(x!=null)return x;String s=l.substring(0,l.length()-3);if(l.endsWith("are"))return s+"ato";if(l.endsWith("ere"))return s+"uto";return s+"ito";}
 private static String[] passato(String l){String pp=participle(l);if(ESSERE_AUX.contains(l)){String p=pp.endsWith("o")?pp.substring(0,pp.length()-1):pp;return new String[]{"sono "+p+"o/a","sei "+p+"o/a","è "+p+"o/a","siamo "+p+"i/e","siete "+p+"i/e","sono "+p+"i/e"};}String[] a=PRESENT_IRR.get("avere");String[] out=new String[6];for(int i=0;i<6;i++)out[i]=a[i]+" "+pp;return out;}
 private static boolean isInf(String s){return s.endsWith("are")||s.endsWith("ere")||s.endsWith("ire");}private static String norm(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}
}
