package com.italiano2774.nativeapp;
import android.os.Bundle;import android.os.SystemClock;import android.view.*;import android.widget.TextView;import androidx.annotation.*;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import java.util.*;
/** Turns the existing family browser into active retrieval practice. */
public class WordFamilyTrainingFragment extends Fragment{
 private static class Q{WordFamily f;WordFamilyMember cue,answer;List<WordFamilyMember> options=new ArrayList<>();}
 private final List<Q> qs=new ArrayList<>();private int idx=0,correct=0;private long started;private ProgressStore progress;private AudioPlayer audio;private WordRepository words;private TextView count,prompt,feedback,summary;private MaterialButton b1,b2,b3,next;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_family_training,c,false);progress=new ProgressStore(requireContext());words=WordRepository.get(requireContext());audio=new AudioPlayer(requireContext(),progress);count=v.findViewById(R.id.text_family_train_counter);prompt=v.findViewById(R.id.text_family_train_prompt);feedback=v.findViewById(R.id.text_family_train_feedback);summary=v.findViewById(R.id.text_family_train_summary);b1=v.findViewById(R.id.button_family_train_1);b2=v.findViewById(R.id.button_family_train_2);b3=v.findViewById(R.id.button_family_train_3);next=v.findViewById(R.id.button_family_train_next);build();b1.setOnClickListener(x->answer(b1));b2.setOnClickListener(x->answer(b2));b3.setOnClickListener(x->answer(b3));next.setOnClickListener(x->{idx++;show();});show();return v;}
 private void build(){List<WordFamily> all=new ArrayList<>(WordFamilyRepository.get(requireContext()).all());List<WordFamilyMember> distractors=new ArrayList<>();for(WordFamily f:all)if(!f.members.isEmpty())distractors.add(f.members.get(0));int made=0;for(WordFamily f:all){if(f.members.size()<2)continue;Q q=new Q();q.f=f;q.cue=f.members.get(0);q.answer=f.members.get(1);q.options.add(q.answer);for(WordFamilyMember d:distractors){if(q.options.size()>=3)break;if(d.id!=q.cue.id&&d.id!=q.answer.id&&WordFamilyRepository.get(requireContext()).familyForWord(d.id)!=f)q.options.add(d);}if(q.options.size()==3){Collections.shuffle(q.options);qs.add(q);made++;if(made>=30)break;}}}
 private void show(){feedback.setVisibility(View.GONE);next.setVisibility(View.GONE);if(idx>=qs.size()){b1.setVisibility(View.GONE);b2.setVisibility(View.GONE);b3.setVisibility(View.GONE);prompt.setText("词族关联训练完成 🎉");count.setText(qs.size()+" / "+qs.size());summary.setVisibility(View.VISIBLE);summary.setText("正确 "+correct+" / "+qs.size()+" · "+Math.round(correct*100.0/Math.max(1,qs.size()))+"%\n通过关联词形、派生词和变位，减少把每个词当成孤立项目记忆。");return;}Q q=qs.get(idx);count.setText((idx+1)+" / "+qs.size()+" · 词族关联");prompt.setText("“"+q.cue.word+"”  "+q.cue.chinese+"\n下面哪个词和它属于同一词族？");set(b1,q.options.get(0));set(b2,q.options.get(1));set(b3,q.options.get(2));started=SystemClock.elapsedRealtime();}
 private void set(MaterialButton b,WordFamilyMember m){b.setTag(m);b.setText(m.word+"\n"+m.chinese);b.setEnabled(true);b.setVisibility(View.VISIBLE);}
 private void answer(MaterialButton b){Q q=qs.get(idx);WordFamilyMember got=(WordFamilyMember)b.getTag();boolean ok=got!=null&&got.id==q.answer.id;long ms=SystemClock.elapsedRealtime()-started;if(ok)correct++;progress.recordAuxiliaryResult("family_train",ok,ms);if(!ok)progress.recordErrorCause(ErrorCause.MEANING_CONFUSION,q.cue.id,"family_train",q.answer.word,got==null?"":got.word,"同一词族应建立关联记忆");feedback.setText((ok?"✅ 正确":"❌ 正确答案："+q.answer.word)+"\n词族："+q.f.title+"\n"+q.f.note);feedback.setVisibility(View.VISIBLE);Word w=words.byId(q.answer.id);if(w!=null)audio.play(w);b1.setEnabled(false);b2.setEnabled(false);b3.setEnabled(false);next.setVisibility(View.VISIBLE);}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
