package com.italiano2774.nativeapp;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.core.content.ContextCompat;import androidx.fragment.app.Fragment;import com.google.android.material.button.MaterialButton;import com.google.android.material.card.MaterialCardView;import java.util.*;
public class WordFamilyFragment extends Fragment{
 private WordFamilyRepository families;private WordRepository words;private ProgressStore progress;private AudioPlayer audio;private Spinner spinner;private TextView stats,title,kind,note,mastery;private LinearLayout members;private int index=0;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_word_families,c,false);families=WordFamilyRepository.get(requireContext());words=WordRepository.get(requireContext());progress=new ProgressStore(requireContext());audio=new AudioPlayer(requireContext(),progress);spinner=v.findViewById(R.id.spinner_family);stats=v.findViewById(R.id.text_family_stats);title=v.findViewById(R.id.text_family_title);kind=v.findViewById(R.id.text_family_kind);note=v.findViewById(R.id.text_family_note);mastery=v.findViewById(R.id.text_family_mastery);members=v.findViewById(R.id.container_family_members);v.findViewById(R.id.button_family_back).setOnClickListener(x->((MainActivity)requireActivity()).openPractice());v.findViewById(R.id.button_family_prev).setOnClickListener(x->{if(index>0){index--;spinner.setSelection(index);}});v.findViewById(R.id.button_family_next).setOnClickListener(x->{if(index+1<families.all().size()){index++;spinner.setSelection(index);}});
  List<String> names=new ArrayList<>();for(WordFamily f:families.all())names.add(f.title+" · "+f.kind);ArrayAdapter<String>a=new ArrayAdapter<>(requireContext(),R.layout.item_spinner_text,names);a.setDropDownViewResource(R.layout.item_spinner_dropdown);spinner.setAdapter(a);spinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View vv,int pos,long id){index=pos;render();}});stats.setText(families.all().size()+" 组词族/词形家族 · 点击成员可听发音");render();return v;}
 private void render(){if(families.all().isEmpty())return;WordFamily f=families.all().get(Math.max(0,Math.min(index,families.all().size()-1)));title.setText(f.title);kind.setText(f.kind+" · "+f.members.size()+"项");note.setText(f.note);int known=0;for(WordFamilyMember m:f.members)if(progress.mastery(m.id)>=3)known++;mastery.setText("本组达到3级+："+known+" / "+f.members.size());members.removeAllViews();for(WordFamilyMember m:f.members){MaterialCardView card=new MaterialCardView(requireContext());card.setRadius(dp(14));card.setStrokeWidth(dp(1));card.setStrokeColor(ContextCompat.getColor(requireContext(),progress.mastery(m.id)>=3?R.color.level4:R.color.line));card.setCardBackgroundColor(ContextCompat.getColor(requireContext(),R.color.surface));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);cp.setMargins(0,dp(4),0,dp(4));members.addView(card,cp);LinearLayout row=new LinearLayout(requireContext());row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(12),dp(10),dp(8),dp(10));card.addView(row);LinearLayout text=new LinearLayout(requireContext());text.setOrientation(LinearLayout.VERTICAL);row.addView(text,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));TextView wv=new TextView(requireContext());wv.setText(m.word);wv.setTextSize(18);wv.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_primary));wv.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);text.addView(wv);TextView zh=new TextView(requireContext());zh.setText(m.chinese+(m.formInfo==null||m.formInfo.isEmpty()?"":" · "+m.formInfo));zh.setTextSize(12);zh.setTextColor(ContextCompat.getColor(requireContext(),R.color.text_secondary));text.addView(zh);MaterialButton listen=new MaterialButton(requireContext());listen.setAllCaps(false);listen.setText("🔊");listen.setMinWidth(0);listen.setOnClickListener(v->audio.speak(m.word));row.addView(listen,new LinearLayout.LayoutParams(dp(54),dp(40)));}}
 private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}@Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
