package com.italiano2774.nativeapp;
import java.text.Normalizer;import java.util.*;
/** Deterministic local writing feedback. It checks task completion and common structural mistakes; it is not AI grading. */
public final class WritingEvaluator{
 public static class Result{public int score;public String feedback="";public List<String> missing=new ArrayList<>();}
 private WritingEvaluator(){}
 private static String n(String s){return Normalizer.normalize(s==null?"":s.toLowerCase(Locale.ITALIAN),Normalizer.Form.NFD).replaceAll("\\p{M}","").replace('’','\'');}
 public static Result evaluate(WritingPrompt p,String answer){Result r=new Result();String a=n(answer);String[] words=a.trim().isEmpty()?new String[0]:a.trim().split("\\s+");int score=Math.min(35,(int)Math.round(words.length*35.0/Math.max(1,p.minWords)));int hit=0;for(String k:p.keywords){String[] alternatives=n(k).split("\\|");boolean ok=false;for(String alt:alternatives)if(!alt.isBlank()&&a.contains(alt.trim())){ok=true;break;}if(ok)hit++;else r.missing.add(k);}if(!p.keywords.isEmpty())score+=Math.round(hit*45f/p.keywords.size());else score+=45;if(a.matches(".*\\b(io|mi|sono|ho|vorrei|devo|posso|vado|abito|lavoro)\\b.*"))score+=10;if(answer!=null&&answer.trim().matches(".*[.!?]$"))score+=5;if(answer!=null&&answer.trim().length()>0&&Character.isUpperCase(answer.trim().charAt(0)))score+=5;r.score=Math.min(100,score);StringBuilder fb=new StringBuilder();fb.append("任务完成度 ").append(r.score).append("/100");if(words.length<p.minWords)fb.append("\n• 建议至少写 ").append(p.minWords).append(" 个词，目前 ").append(words.length).append(" 个。 ");if(!r.missing.isEmpty())fb.append("\n• 可以补上这些关键信息：").append(String.join("、",r.missing));if(a.contains("io e")&&a.matches(".*\\bio e\\s+\\w+\\s+e\\b.*"))fb.append("\n• 注意主语复数时动词也要使用复数形式。");if(a.contains("ho bisogno")&&!a.contains("ho bisogno di"))fb.append("\n• 固定搭配是 avere bisogno di。");if(a.contains("vado in roma")||a.contains("sono in roma"))fb.append("\n• 城市名前通常使用 a：a Roma。 ");if(r.score>=80)fb.append("\n✓ 这段表达已经能完成任务，可以再对照参考表达让句子更自然。");r.feedback=fb.toString();return r;}
}
