#!/usr/bin/env python3
import json
from pathlib import Path
P=Path(__file__).resolve().parents[1]/'app/src/main/assets/words.json'
D=json.loads(P.read_text(encoding='utf-8'))
EX={
'zucchero':('Prendo il caffè senza zucchero.','我喝咖啡不加糖。'),
'arrivederci':('Arrivederci, a domani!','再见，明天见！'),
'cappuccino':('Vorrei un cappuccino, per favore.','请给我一杯卡布奇诺。'),
'gelato':('Prendo un gelato al cioccolato.','我要一个巧克力冰淇淋。'),
'no':('No, grazie. Va bene così.','不用了，谢谢。这样就可以。'),
'ma':('Vorrei venire, ma oggi lavoro.','我想来，但是今天我要工作。'),
'latte':('Prendo un caffè con latte.','我要一杯加牛奶的咖啡。'),
'sì':('Sì, va bene per me.','好的，我没问题。'),
'grazie':('Grazie per il suo aiuto.','谢谢您的帮助。'),
'con':('Vado al lavoro con Marco.','我和马尔科一起去上班。'),
'caffè':('Prendo un caffè al bar.','我在咖啡吧喝一杯咖啡。'),
'un':('Vorrei un biglietto per Milano.','我想要一张去米兰的票。'),
'salve':('Salve, avrei bisogno di un’informazione.','您好，我想咨询一个信息。'),
'tè':('La sera bevo una tazza di tè.','晚上我喝一杯茶。'),
'per favore':('Può parlare più lentamente, per favore?','请您说慢一点可以吗？'),
'cornetto':('A colazione prendo un cornetto.','早餐我吃一个羊角面包。'),
'di dove sei':('Di dove sei? Sono di Shanghai.','你来自哪里？我来自上海。'),
'caro':('Questo ristorante è troppo caro.','这家餐厅太贵了。'),
'tu':('Tu lavori oggi?','你今天上班吗？'),
'sei':('Sei libero domani pomeriggio?','你明天下午有空吗？'),
'scusa':('Scusa, dov’è la stazione?','不好意思，火车站在哪里？'),
'vero':('È vero, hai ragione.','是真的，你说得对。'),
'Milano':('Vivo a Milano.','我住在米兰。'),
'Roma':('Domani vado a Roma in treno.','明天我坐火车去罗马。'),
'piacere':('Piacere, mi chiamo Li.','很高兴认识你，我叫李。'),
'tonno':('Vorrei un panino al tonno.','我想要一个金枪鱼三明治。'),
'sono':('Sono stanco, ma sto bene.','我累了，不过我很好。'),
'io':('Io studio italiano ogni giorno.','我每天学习意大利语。'),
'ciao':('Ciao, come stai?','你好，你怎么样？'),
'italiana':('La cucina italiana mi piace molto.','我很喜欢意大利菜。'),
'figlio':('Mio figlio va a scuola.','我儿子去上学。'),
'mano':('Mi fa male la mano destra.','我的右手疼。'),
'o':('Preferisci il tè o il caffè?','你喜欢茶还是咖啡？'),
'che':('Che cosa devo fare adesso?','我现在应该做什么？'),
'moglie':('Mia moglie lavora a Milano.','我妻子在米兰工作。'),
'marito':('Mio marito torna a casa alle sette.','我丈夫七点回家。'),
'figlia':('Mia figlia studia all’università.','我女儿在大学学习。'),
'madre':('Mia madre vive con noi.','我母亲和我们一起住。'),
'una':('Vorrei una bottiglia d’acqua.','我想要一瓶水。'),
'lei':('Lei parla inglese?','您会说英语吗？'),
'uovo':('A colazione mangio un uovo.','早餐我吃一个鸡蛋。'),
'lui':('Lui lavora vicino a casa.','他在家附近工作。'),
'padre':('Mio padre è in pensione.','我父亲已经退休了。'),
'bello':('È un posto molto bello.','这是一个很漂亮的地方。'),
'dare':('Può darmi una ricevuta?','您可以给我一张收据吗？'),
'pizzeria':('Stasera andiamo in pizzeria.','今晚我们去披萨店。'),
'questa':('Quanto costa questa giacca?','这件夹克多少钱？'),
'grazie mille':('Grazie mille per la disponibilità.','非常感谢您的帮助。'),
'farmacia':('Dov’è la farmacia più vicina?','最近的药店在哪里？'),
'bar':('Ci vediamo al bar alle nove.','我们九点在咖啡吧见。'),
'questo':('Vorrei comprare questo.','我想买这个。'),
'quale':('Quale autobus devo prendere?','我应该坐哪辆公交车？'),
'e':('Compro pane e latte.','我买面包和牛奶。'),
'ristorante':('Abbiamo prenotato un tavolo al ristorante.','我们在餐厅订了一张桌子。'),
'banca':('Devo andare in banca questa mattina.','我今天上午得去银行。'),
'bagno':('Scusi, dov’è il bagno?','不好意思，请问洗手间在哪里？'),
'chiesa':('La chiesa è vicino alla piazza.','教堂在广场附近。'),
'signora':('Buongiorno, signora. Posso aiutarla?','您好，女士。我可以帮您吗？'),
"c'è":("C’è una farmacia qui vicino?",'这附近有药店吗？'),
'piazza':('La fermata è dall’altra parte della piazza.','车站在广场的另一边。'),
"dov'è":('Dov’è la fermata dell’autobus?','公交车站在哪里？'),
'qui':('Può firmare qui, per favore?','请您在这里签字。'),
'teatro':('Il teatro è aperto stasera.','剧院今晚开放。'),
'negozio':('Il negozio chiude alle otto.','商店八点关门。'),
'signore':('Mi scusi, signore.','不好意思，先生。'),
'timido':('Sono un po’ timido quando parlo italiano.','我说意大利语时有一点害羞。'),
'amico':('Un mio amico vive a Torino.','我的一个朋友住在都灵。'),
'simpatico':('Il nuovo collega è molto simpatico.','新同事很友好。'),
'il mio':('Questo è il mio documento.','这是我的证件。'),
"un'":("Vorrei un’acqua naturale.",'我想要一瓶常温矿泉水。'),
'la mia':('Questa è la mia tessera sanitaria.','这是我的医保卡。'),
'amica':('Una mia amica studia italiano con me.','我的一位女性朋友和我一起学意大利语。'),
'ha':('Ha un appuntamento?','您有预约吗？'),
'ragazza':('La ragazza alla cassa parla inglese.','收银台的女孩会说英语。'),
'americana':('Lei è americana, ma vive in Italia.','她是美国人，但住在意大利。'),
'ho':('Ho bisogno di aiuto.','我需要帮助。'),
'vicina':('La farmacia è molto vicina.','药店非常近。'),
'ragazzo':('Quel ragazzo aspetta l’autobus.','那个男孩在等公交车。'),
'americano':('Lui è americano.','他是美国人。'),
'vicino':('Abito vicino alla stazione.','我住在火车站附近。'),
'mai':('Non sono mai stato a Napoli.','我从来没有去过那不勒斯。'),
'hai':('Hai già comprato il biglietto?','你已经买票了吗？'),
'tiramisù':('Come dolce prendo il tiramisù.','甜点我要提拉米苏。'),
'come dolce':('Come dolce, cosa mi consiglia?','甜点您推荐什么？'),
'conto':('Il conto, per favore.','请结账。'),
'torta':('Vorrei una fetta di torta.','我想要一块蛋糕。'),
'a presto':('Grazie, a presto!','谢谢，回头见！'),
'notte':('Buona notte, a domani.','晚安，明天见。'),
'casa':('Torno a casa alle sei.','我六点回家。'),
'pollo':('Per secondo prendo il pollo.','第二道菜我吃鸡肉。'),
'pesce':('Oggi preferisco il pesce.','今天我更想吃鱼。'),
'riso':('Mangio spesso riso a pranzo.','我午饭经常吃米饭。'),
'pasta':('La pasta è pronta.','意大利面做好了。'),
'come primo':('Come primo prendo la pasta.','第一道菜我要意大利面。'),
'come secondo':('Come secondo prendo il pesce.','第二道菜我要鱼。'),
'insalata':('Vorrei un’insalata senza cipolla.','我想要一份不放洋葱的沙拉。'),
'antipasto':('Prendiamo un antipasto da condividere.','我们点一份前菜一起吃。'),
'vorrei':('Vorrei fissare un appuntamento.','我想预约一个时间。'),
'buon giorno':('Buon giorno, ho un appuntamento alle dieci.','早上好，我十点有预约。'),
'prego':('Grazie. — Prego.','谢谢。——不客气。'),
'menù':('Possiamo avere il menù, per favore?','可以给我们菜单吗？'),
'ecco':('Ecco il mio passaporto.','这是我的护照。'),
'tavolo':('Vorrei prenotare un tavolo per due.','我想预订一张两人桌。'),
'quanto costa':('Quanto costa questo biglietto?','这张票多少钱？'),
'euro':('Costa dieci euro.','它十欧元。'),
'dieci':('L’appuntamento è alle dieci.','预约时间是十点。'),
'cinquanta':('Sono cinquanta euro in tutto.','一共五十欧元。'),
'piccola':('Vorrei una bottiglia piccola.','我想要一小瓶。'),
'nera':('Preferisco la borsa nera.','我更喜欢黑色的包。'),
'acqua':('Vorrei una bottiglia d’acqua naturale.','我想要一瓶常温矿泉水。'),
'pane':('Compro il pane ogni mattina.','我每天早上买面包。'),
'buongiorno':('Buongiorno, come posso aiutarla?','您好，我能怎么帮您？'),
'buonasera':('Buonasera, ho una prenotazione.','晚上好，我有预订。'),
'domani':('Ci vediamo domani mattina.','我们明天上午见。'),
'oggi':('Oggi devo andare in Comune.','今天我得去市政府。'),
'adesso':('Che cosa devo fare adesso?','我现在应该做什么？'),
'aiuto':('Ho bisogno di aiuto, per favore.','我需要帮助。'),
'documento':('Questo documento è valido?','这份文件有效吗？'),
'appuntamento':('Ho un appuntamento alle undici.','我十一点有预约。'),
'biglietto':('Vorrei un biglietto di sola andata.','我想要一张单程票。'),
'stazione':('La stazione è lontana da qui?','火车站离这里远吗？'),
'autobus':('Quale autobus va in centro?','哪辆公交车去市中心？'),
'treno':('Il treno parte dal binario cinque.','火车从五号站台出发。'),
'ospedale':('Devo andare in ospedale.','我得去医院。'),
'medico':('Vorrei parlare con un medico.','我想和医生谈一下。'),
'lavoro':('Vado al lavoro alle otto.','我八点去上班。'),
}
GRAM={
'cornetto':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='cornetti'),
'tonno':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='tonni'),
'pizzeria':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='pizzerie'),
'cielo':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='cieli'),
'luna':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='lune'),
'mano':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='mani'),
'piazza':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='piazze'),
'bagno':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='bagni'),
'signora':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='signore'),
'signore':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='signori'),
'ragazza':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='ragazze'),
'ragazzo':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='ragazzi'),
'tiramisù':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='tiramisù'),
'notte':dict(partOfSpeech='noun',gender='f',number='singular',article='la',plural='notti'),
'antipasto':dict(partOfSpeech='noun',gender='m',number='singular',article="l'",plural='antipasti'),
'menù':dict(partOfSpeech='noun',gender='m',number='singular',article='il',plural='menù'),
}
updated=grammar=0
for x in D:
    w=x.get('word','')
    if w in EX:
        x['example'],x['exampleZh']=EX[w];updated+=1
    if w in GRAM:
        for k,v in GRAM[w].items():x[k]=v
        grammar+=1
P.write_text(json.dumps(D,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
report={'version':'2.2','curatedSurfaceForms':len(EX),'rowsWithCuratedExamples':updated,'rowsWithGrammarCorrections':grammar,'totalRows':len(D),'scope':'首批高频日常词与生活表达，后续继续滚动精修'}
(Path(__file__).resolve().parents[1]/'app/src/main/assets/word_quality_v22.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(report)
